### ISSUE TITLE
Personal data export stopped working

### ISSUE THREAD

**Issue by Craftoncu** [go-vikunja/vikunja#110]
### Description

Hey @kolaente,

I found out, that in your latest two versions of vikunja-api the personal data export isn't working anymore. I get some exception in the pod logs. 

`2024-01-29 23:55:48.461Z,vikunja-api-6fd578c799-kv874,vikunja-api,"1:00 [31m2024-01-29T22:55:48.461257753Z: ERROR	▶ events/func1 438[0m Error while handling message a1da579c-b5a9-4fdd-902f-069ccb9d0cdc, topic_poisoned=user.export.requested, handler_poisoned=user.export.requested.handle.user.data.export, subscriber_poisoned=gochannel.GoChannel, reason_poisoned=open ./persistent/files/11: no such file or directory,  payload={"user":{"id":1,"name":"<redacted>","username":"<redacted>","created":"2023-08-16T22:09:55+02:00","updated":"2024-01-11T02:00:00+01:00"}}"
`

I checked the given file path. And the file is missing. Its not a clean install. The upgrade path started in v.0.21 I think.
Hope you can reproduce this issue. 

Just tell me if you need further information or assistance. 

Thanks,
Daniel

### Vikunja Frontend Version

v0.22.1

### Vikunja API Version

v0.22.1

### Browser and version

-

### Can you reproduce the bug on the Vikunja demo site?

No

**Comment by kolaente** [comment]
This looks like one of the saved files was deleted without the corresponding database entry. Still, neither that nor the crash should happen. I'll take a look.

**Comment by Craftoncu** [comment]
Thanks!
FYI: The deletion was not initiated manually.
I can't tell you, where the files went.

**Comment by kolaente** [comment]
Pushed a fix in https://github.com/go-vikunja/vikunja/commit/7edb53ca12096560a20732e9232702910df86c9c - now the export won't crash when a file does not exist.
