### ISSUE TITLE
Question: Notification of subscribed project missing

### ISSUE THREAD

**Issue by Bavarianspirit** [go-vikunja/vikunja#113]
### Description

Hey @kolaente,

in Vikunja there is a feature to subscribe to specific topics and tasks.
But is it possible to receive a email notification if someone adds a comment or changes the task or creates or changes a task in a subscribed project?

### Vikunja Frontend Version

0.22.1

### Vikunja API Version

0.22.1

### Browser and version

-

### Can you reproduce the bug on the Vikunja demo site?

No

**Comment by Craftoncu** [comment]
Can anyone relate this issue? I tried with 0.22.1 and it's the same to me.

**Comment by kolaente** [comment]
There have been some improvements to the notifications in the last release (0.23.0). Do you still have the same issues if you try it with that?

**Comment by kolaente** [comment]
Closing as resolved and inactive, please ping if you still have issues.
