### ISSUE TITLE
Task editing UI continuously re-renders, causing high CPU usage and some UI issues

### ISSUE THREAD

**Issue by GottemHams** [go-vikunja/vikunja#125]
### Description

I'm not 100% sure if this is an issue with the Vikunja frontend itself or one of the frameworks it uses (I think it's Vue/Vite?), but it seems most appropriate to start here. I tried searching in all mentioned repositories for some parts of the JavaScript I've shown further below but nothing came up. The issue only seems to exist on Firefox and occurs even in safe mode (all addons disabled), although I've only tested with Chrome besides.

It looks like almost the entire UI is continuously being re-rendered when the edit task page is open, even without any interaction with **any** part of the UI. This happens regardless of the task UI being rendered in a modal (e.g. opening a task from the kanban view) or in its own separate page (e.g. from list view). Firefox's developer console highlights modified nodes with a yellow background, which [as you can see are quite a lot of nodes](https://github.com/go-vikunja/frontend/assets/20195269/99f16dbe-8fb5-43ac-9ece-602db2a69707).

The re-render happens fast enough that all those nodes are never **not** highlighted, which causes [a major spike in CPU usage](https://github.com/go-vikunja/frontend/assets/20195269/c4b32258-8227-4b8b-9ecc-75a37b699998). When the task UI is in a modal and I close it, CPU usage immediately drops back down to sub 1% or even "idle", so it's not an issue with the page it was shown on.

It also causes some side effects with usability of the UI, particularly an opened `select` input which keeps resetting the selection to its current value (e.g. the task relation type input). This again happens very fast, it's nearly impossible to select the value you actually want. Unless you know exactly what you need and can use your keyboard to change the value while it has focus (but not opened). [Here's a lil' screen recording](https://github.com/go-vikunja/frontend/assets/20195269/86e78645-af50-41fe-9ff7-b488ff386c1d). Text inputs seem unaffected at least.

Since even the document's root (`<html>`) is being modified, I decided to add a breakpoint on that tag for attribute modifications. It seems a certain attribute is continuously being added and removed, and due to the reactiveness of Vue/Vite it also re-renders a whole bunch of child components every time? First it showed me `<html class="dark" q-has-scope5301926="" lang="en">` and 2 breakpoints later it becomes `<html class="dark" q-has-scope5218981="" lang="en">`. The JS code the debugger is breaking on:
```js
var Be = 'q-has-scope' + (Math.floor(9000000 * Math.random()) + 1000000);
ze.setAttribute(Be, '');

// Then the breakpoint after that:
if (ze.removeAttribute(Be), Ve.length > 0) {
```

As I've mentioned in the starting paragraph: I tried searching for some key parts of this JS in Vue/Vite/Vikunja repos (hoping to find the unobfuscated source) and I couldn't find anything, hence why I'm not sure in what part of the chain this problem exists.

I created a [new task on the demo site](https://try.vikunja.io/tasks/43) and I have the same issue there.

### Vikunja Frontend Version

0.22.0

### Vikunja API Version

0.22.0

### Browser and version

Firefox ESR 115.6.0

### Can you reproduce the bug on the Vikunja demo site?

Yes

**Comment by kolaente** [comment]
There have been a few updates to tiptap in the meantime, can you still reproduce this?

**Comment by GottemHams** [comment]
Nope, seems to be good now, it's barely even making a mark on CPU usage. :> For completeness, I'm on Vikunja 0.24.2 but Firefox was still v115.6.0 ESR. After the successful test I decided to also update Firefox (to 115.15.0) and check again. Somehow it still had something cached from the old Vikunja version because the problem re-occurred, but Vikunja also showed the bar at the bottom about an "update" being available. Letting it reload one last time once again fixes the issue, so it was definitely something in Tiptap I'd say.
