### ISSUE TITLE
Unable to filter tasks by exclusive labels

### ISSUE THREAD

**Issue by isogashiiman** [go-vikunja/vikunja#127]
### Description

When I am on a view with a task list,
Upon opening the 'Filters' modal and adding 2 labels, **The search result displays all tasks with at least one of the 2 labels**,
regardless of whether I select "_Require all filters to be true for a task to show up_" or not.

Expected result: **Only tasks that have both labels should be shown**,
or an explicit checkbox indicating whether the result is inclusive or exclusive.

I can provide screenshots to illustrate if needed. if this problem is in an inappropriate section, let me know and I'll report it to the api repo.

### Vikunja Frontend Version

0.22.0+2-e98e5a0d2f

### Vikunja API Version

v0.22.0+3-d952bedce0

### Can you reproduce the bug on the Vikunja demo site?

Yes

**Comment by kolaente** [comment]
We now have query based filter logic in https://kolaente.dev/vikunja/vikunja/pulls/2177. Please check with the next unstable build if that fixes your problem.
