### ISSUE TITLE
Close existing 'Defer due date' window when opening another

### ISSUE THREAD

**Issue by StrangePeanut** [go-vikunja/vikunja#131]
### Description

Opening another 'Defer due date' window causes the initial window to overlap the new one.

### Vikunja Frontend Version

0.21.0+315-963d91c4d5

### Vikunja API Version

v0.21.0+189-66afe52afb

### Browser and version

Version 1.59.124 Chromium: 118.0.5993.117 (Official Build) (64-bit)

### Can you reproduce the bug on the Vikunja demo site?

Yes

### Screenshots

![Initial-window-overlapping-the-other](https://github.com/go-vikunja/frontend/assets/56807288/26bc29e8-83b6-41e8-a4c9-ba1a9b5a31a3)

**Comment by kolaente** [comment]
Fixed in https://github.com/go-vikunja/vikunja/commit/4c55016c1a450f75f0a8c5acd8ed01517ed08a1d, please check with the next unstable build (should be ready for deployment in ~45min, also on [try](https://try.vikunja.io)).
