### ISSUE TITLE
Minor error in documentation

### ISSUE THREAD

**Issue by n00b12345** [go-vikunja/vikunja#222]
### Description

In the documentation [here](https://vikunja.io/docs/full-docker-example/#example-without-any-proxy) (example without any proxy section), the passwords for the MYSQL_PASSWORD and VIKUNJA_DATABASE_PASSWORD should match.

In the example provided, they don't. It might confuse new users. Please consider changing it.

### Vikunja Version

0.23.0

### Can you reproduce the bug on the Vikunja demo site?

No

### Screenshots

![Screenshot 2024-02-12 134138](https://github.com/go-vikunja/vikunja/assets/17707852/78ff0633-b737-4678-b724-d095fb2d78d7)

**Comment by kolaente** [comment]
Thanks! Fixed in 18374c2e52a78d48698945981fb59ea3a86eff12
