### ISSUE TITLE
Problems with the desktop electron app

### ISSUE THREAD

**Issue by lerra** [go-vikunja/vikunja#223]
### Description

Since I upgraded to 0.23 I can not use the desktop app on ubuntu, I tried both the snap and dep package with same result,
"Could not find or use Vikunja installation at "vikunja.x.x". Please check if the url has the correct format and you can reach it when accessing it directly and try again."

The url is set to https://vikunja.x.x/api/v1, I also tried only https://vikunja.x.x/

I see successful 200 get requests to https://vikunja.x.x/api/v1/info, it works if I browse directly to https://vikunja.x.x/ or using the android app,

For some reason when I check tcpdump it does try to connect to port 3456 even if I configured it only for https on standard 443 port in the env variable for docker

Any idea what I am doing wrong or did I hit a bug? It worked like a charm before I did the update to 0.23 and followed the instructions

### Vikunja Version

0.23

### Browser and version

electron

### Can you reproduce the bug on the Vikunja demo site?

No

**Comment by kolaente** [comment]
Does your Vikunja instance have CORS enabled? Does it work with `https://try.vikunja.io`?

**Comment by lerra** [comment]
It works with try.vikunja.io and I found the problem

Root cause: Me going through the blog post upgrade text a bit to fast, it says what needs to be changed but it would be nice to make it even more clear

Solution
Change from thefrontend env to VIKUNJA_SERVICE_PUBLICURL and add VIKUNJA_CORS_ENABLE
