### ISSUE TITLE
Reminder in minutes before a date changes date to 31 Dec 1969, 21:00:00

### ISSUE THREAD

**Issue by lelemm** [go-vikunja/vikunja#225]
### Description

Set start date
Add new reminder -> custom -> 2 / minutes / before / start date -> confirm
Reminder gets set to 31 Dec 1969, 21:00:00

### Vikunja Version

Version: v0.23.0+69-837360f122

### Browser and version

Chrome

### Can you reproduce the bug on the Vikunja demo site?

Yes

### Screenshots

![image](https://github.com/go-vikunja/vikunja/assets/15043428/dc5d622d-5a4f-468b-b2d1-a53b4d0e64b1)

**Comment by kolaente** [comment]
Does this also happen when you add a start date, reload the page and then add a reminder?

**Comment by lelemm** [comment]
Yes. Tried multiple times, same result

**Comment by kolaente** [comment]
Fixed in ccb708a56f283e957c71c165190d0f415a9788e5, please check with the next unstable build (should be ready for deployment in ~45min, also on [try](https://try.vikunja.io)).

**Comment by lelemm** [comment]
Tried at demo instance @kolaente, there is something wrong cuz as soon as I select any value in any dropdown the reminder is saved before I can interact with any other dropdown. See the video below:


https://github.com/go-vikunja/vikunja/assets/15043428/70162b97-4422-4462-acde-f794ef149eae

**Comment by kolaente** [comment]
Should now be fixed in 403db6adbf9ef5891756322563bb24b3b1c5035f - please check again in the next unstable build.

**Comment by lelemm** [comment]
Nice, it now waits for my input. The only problem I see is that when you put a reminder minutes before, it shows as a fraction of hour, see the video bellow:


https://github.com/go-vikunja/vikunja/assets/15043428/6edfeff9-5f41-41d4-9012-265eb0d79974

**Comment by kolaente** [comment]
The issue with reminder minutes should be fixed in https://github.com/go-vikunja/vikunja/commit/fd520dab0a6767eb47a98b04cd3f833f337218e5, please check with the next unstable build (should be ready for deployment in ~45min, also on [try](https://try.vikunja.io)).
