### ISSUE TITLE
Fresh desktop install cannot connect to any servers

### ISSUE THREAD

**Issue by codevski** [go-vikunja/vikunja#226]
### Description

So I have a docker selfhosted instance which works fine in the browser but when I try to setup desktop app I cannot seem to get it to connect. I have also tried connecting to official (saw someone say to test it regarding another issue someone was having and I still cannot connect.

### Vikunja Version

"v0.23.0"

### Browser and version

Desktop: Both Flatpak and AUR bin 0.23.0-1

### Can you reproduce the bug on the Vikunja demo site?

No

### Screenshots

![image](https://github.com/go-vikunja/vikunja/assets/1435321/b5d252cf-eb46-4e9e-a8d2-2833cd00edf8)

**Comment by kolaente** [comment]
Can you check what the API response is when you set the url? (CTRL+Shift+I and then "network")

**Comment by Protarios** [comment]
Here a Screenshot from my desktop app. I experience the same issue.

![Screenshot_20240301_090152](https://github.com/go-vikunja/vikunja/assets/11992477/da1defa4-ac94-4cdb-9454-f1d9ead1b398)

**Comment by kolaente** [comment]
Did you enable [cors](https://vikunja.io/docs/config-options/#cors)?

**Comment by Protarios** [comment]
Let me check. It stopped working, when I updated from the seperate frontend/backend containers to the new integrated one.

**Comment by Protarios** [comment]
I am playing around with cors and port settings a bit, maybe the issue lies there.

This is the exact step in the code where it stops.
![Screenshot_20240301_091144](https://github.com/go-vikunja/vikunja/assets/11992477/197ceec7-ef2e-4cb9-af73-49c7530f0ab3)

**Comment by kolaente** [comment]
The network error from the screenshot you sent before said "CORS Error". That's a pretty strong indication that you didn't enable CORS. Does it work if you enable it?

**Comment by kolaente** [comment]
In the dev tools, what's the value of the `access-control-allow-origin` header in the response of the request to `/info`?

**Comment by Protarios** [comment]
![Uploading Screenshot_20240301_102834.png…]()

**Comment by cerealconyogurt** [comment]
Hey! I have the same issue.  I have a self-hosted instance running and working fine in the browser but when I try to setup desktop app I cannot seem to get it to connect. I tried my instance and the official one with both having same access problem.

![image](https://github.com/go-vikunja/vikunja/assets/49502224/c6f6b3b5-8111-4a7c-806b-c73fb7cebfe3)

**Comment by kolaente** [comment]
@cerealconyogurt What do you see in the dev tools? (ctrl + shift + I)

**Comment by brunotenisi** [comment]
I have the same issue. I have a self-hosted instance running and working fine in the browser and in the android app, but when I try to setup desktop app I cannot seem to get it to connect. I tried my instance (flatpak and .RPM) and the official one with both having same access problem.
In the dev tools, there is this error message: 
![Pasted image](https://github.com/go-vikunja/vikunja/assets/48738321/a6e63c07-7680-46ce-9dc8-f28a458de0cd)

**Comment by brunotenisi** [comment]
I have the same issue. I have a self-hosted instance running and working fine in the browser and in the android app, but when I try to setup desktop app I cannot seem to get it to connect. I tried my instance (flatpak and .RPM) and the official one with both having same access problem.
In the dev tools, there is this error message:
![Pasted image](https://github.com/go-vikunja/vikunja/assets/48738321/5d8afc05-0be3-4d04-9f5f-b20d7aa92e72)

**Comment by brunotenisi** [comment]
I tried to move the config.yml to /etc/vikunja in the server, but without success

**Comment by kolaente** [comment]
@brunotenisi Does it work if you set `VIKUNJA_CORS_ENABLE`? The default value for origins is `*`.

**Comment by brunotenisi** [comment]
> @brunotenisi Does it work if you set `VIKUNJA_CORS_ENABLE`? The default value for origins is `*`.

Hello @kolaente, thank you for reply. I found the answer in a post in the vikunja community, [here](https://community.vikunja.io/t/vikunja-desktop-not-working-since-upgrade-to-vikunja-vikunja/2048). 

The fix was to add VIKUNJA_CORS_ENABLE: true to the docker compose environment.

After this,  had to take the dockers down, and put them up again.

**Comment by codevski** [comment]
> > @brunotenisi Does it work if you set `VIKUNJA_CORS_ENABLE`? The default value for origins is `*`.
> 
> Hello @kolaente, thank you for reply. I found the answer in a post in the vikunja community, [here](https://community.vikunja.io/t/vikunja-desktop-not-working-since-upgrade-to-vikunja-vikunja/2048).
> 
> The fix was to add VIKUNJA_CORS_ENABLE: true to the docker compose environment.
> 
> After this, had to take the dockers down, and put them up again.

Tried this out and can confirm this works.  Thanks for the update!
