### ISSUE TITLE
Desktop app does not accept all top level domains

### ISSUE THREAD

**Issue by CyberTechArmor** [go-vikunja/vikunja#229]
### Description

It does not seem that the desktop app recognizes .app as a domain. When I attempted to use .com it tried to connect. Because there is no way for to trigger a manual connect I'm unable to use my.website.app or https://my.website.app.

### Vikunja Version

0.22.1

### Browser and version

Chrome Version 122.0.6261.70 (Official Build) (64-bit)

### Can you reproduce the bug on the Vikunja demo site?

No

**Comment by kolaente** [comment]
Vikunja does not look for a domain ending. Can you reach the api at `https://my.website.app/api/v1/info`? Do you have [cors](https://vikunja.io/docs/config-options/#cors) enabled?

**Comment by CyberTechArmor** [comment]
Adding /api/v1 resolved the issue:

my.website.app/api/v1

Side note, it defaulted to http:// and not https://. I was able to resolve to my site once I updated to https://my.website.app/api/v1

I appreciate the quick response.
