### ISSUE TITLE
n8n node, (Task) Get Many (List: Projects)

### ISSUE THREAD

**Issue by CyberTechArmor** [go-vikunja/vikunja#230]
### Description

I am able to use the n8n to pull query projects, and to get all tasks by specifying the project by ID. But, the "By List" feature does not populate the projects:

By List:
![image](https://github.com/go-vikunja/vikunja/assets/63061216/7f7ad02a-9126-40b4-b109-54ef41104989)

By Project ID:
![image](https://github.com/go-vikunja/vikunja/assets/63061216/32199dab-e150-4824-b6cf-878c6d7db3a6)

### Vikunja Version

0.22.1

### Browser and version

Chrome Version 122.0.6261.70 (Official Build) (64-bit)

### Can you reproduce the bug on the Vikunja demo site?

No

**Comment by kolaente** [comment]
Does the api token you're using have permission to read all projects?

**Comment by CyberTechArmor** [comment]
I believe all permissions are enabled:

![image](https://github.com/go-vikunja/vikunja/assets/63061216/fe7fbe84-4956-4861-bbfb-2365c6e460e6)

**Comment by kolaente** [comment]
Is there anything in Vikunja's logs when you try to select by list?

**Comment by kolaente** [comment]
Closing as inactive, please ping or open a new issue with relevant information if you still have this problem.

**Comment by prevail90** [comment]
mine says that the view id is 0 when I put a fixed number of 12 or i give it a tag from a pulled all views node
