### ISSUE TITLE
Frontend hangs when opening a task (process crash/eternal loop)

### ISSUE THREAD

**Issue by simeoncode** [go-vikunja/vikunja#233]
### Description

Hello, I managed to import some Trello tasks but the browser freezes when visiting a task. In the attached screenshots, I cannot interact with the browser tab (also visible is the "Stop" button which means that the browser is suggesting to stop the faulty tab JS process).

This doesn't happen when clicking on manually created tasks. The crash happens also when visiting regardless of browsing to the task URL directly (/task/<id>) or going to the project and clicking on the task.

I'm attaching screenshots and a Firefox Profiler profile result.

This is the JSON returned from the backend, for this particular task:
```json
{
  "id": 37,
  "title": "Order phone and port number",
  "description": "",
  "done": false,
  "done_at": "0001-01-01T00:00:00Z",
  "due_date": "0001-01-01T00:00:00Z",
  "reminders": null,
  "project_id": 4,
  "repeat_after": 0,
  "repeat_mode": 0,
  "priority": 0,
  "start_date": "0001-01-01T00:00:00Z",
  "end_date": "0001-01-01T00:00:00Z",
  "assignees": null,
  "labels": null,
  "hex_color": "",
  "percent_done": 0,
  "identifier": "#3",
  "index": 3,
  "related_tasks": {},
  "attachments": null,
  "cover_image_attachment_id": 0,
  "is_favorite": false,
  "created": "2024-03-11T10:55:02Z",
  "updated": "2024-03-11T10:55:02Z",
  "bucket_id": 12,
  "position": 196608,
  "kanban_position": 196607,
  "created_by": {
    "id": 1,
    "name": "",
    "username": "<redacted>",
    "created": "2024-03-11T10:24:27Z",
    "updated": "2024-03-11T11:37:43Z"
  }
}
```

### Vikunja Version

v0.23.0+230-3b77fff4c9

### Browser and version

Firefox + Chrome (both latest)

### Can you reproduce the bug on the Vikunja demo site?

No

### Clicking on the task, from project view
<img width="1276" alt="bild" src="https://github.com/go-vikunja/vikunja/assets/1130096/63005e3f-54ee-426f-bd9a-c33a4cbb7b20">

### Visiting the task URL directly
<img width="1277" alt="bild" src="https://github.com/go-vikunja/vikunja/assets/1130096/8da15077-e1f4-4770-9c8a-ffbc96e3c617">

### Profiler result
[Firefox 2024-03-12 14.37 profile.json.gz](https://github.com/go-vikunja/vikunja/files/14573810/Firefox.2024-03-12.14.37.profile.json.gz)

**Comment by kolaente** [comment]
If you open the dev tools, are there any errors logged in the console when you open the task?

**Comment by devikrishnamk0123** [comment]
we have also faced the same issue. 
The following are the steps used to reproduce the issue


- Ran the application in docker using the **unstable** version of the image.
- Imported a board from trello as user1
- Logged in as user1
- From the imported board, user1 was able to view all tasks, click on a particular task and view it.
- Logged in as user2.
- From the imported board, the frontend hangs when user2 clicks on a particular task.

![image](https://github.com/go-vikunja/vikunja/assets/51746080/6f64e49e-c788-42ea-97b9-482bb36c3e7c)

**Comment by simeoncode** [comment]
> If you open the dev tools, are there any errors logged in the console when you open the task?

<img width="1710" alt="bild" src="https://github.com/go-vikunja/vikunja/assets/1130096/1882443b-72f5-4cb4-85ee-db52ffdc9b63">

**Comment by kolaente** [comment]
I think I've commented this elsewhere already, but can you reproduce this with all tasks or only a specific task? Which attributes does the task have? Are you able to reproduce this on [try](https://try.vikunja.io)?

**Comment by devikrishnamk0123** [comment]
> > If you open the dev tools, are there any errors logged in the console when you open the task?
> 
> <img alt="bild" width="1710" src="https://private-user-images.githubusercontent.com/1130096/316977391-1882443b-72f5-4cb4-85ee-db52ffdc9b63.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTIxMzc4ODcsIm5iZiI6MTcxMjEzNzU4NywicGF0aCI6Ii8xMTMwMDk2LzMxNjk3NzM5MS0xODgyNDQzYi03MmY1LTRjYjQtODVlZS1kYjUyZmZkYzliNjMucG5nP1gtQW16LUFsZ29yaXRobT1BV1M0LUhNQUMtU0hBMjU2JlgtQW16LUNyZWRlbnRpYWw9QUtJQVZDT0RZTFNBNTNQUUs0WkElMkYyMDI0MDQwMyUyRnVzLWVhc3QtMSUyRnMzJTJGYXdzNF9yZXF1ZXN0JlgtQW16LURhdGU9MjAyNDA0MDNUMDk0NjI3WiZYLUFtei1FeHBpcmVzPTMwMCZYLUFtei1TaWduYXR1cmU9Y2UxZGRjZjYyODM3YTdkMmJhNjhhYmRjODEzMmJjZTY1MDg0NTMyNzFmNjVhMjk3MWNmZGFlMzYzNjFjZDM3OCZYLUFtei1TaWduZWRIZWFkZXJzPWhvc3QmYWN0b3JfaWQ9MCZrZXlfaWQ9MCZyZXBvX2lkPTAifQ.2JWoP16OMt7UpyhLVct8CEMu3HXI7-HZrDcXYcOss1k">

No errors are shown in the console
![image](https://github.com/go-vikunja/vikunja/assets/51746080/a0a886f9-cc76-435b-ad98-6f08b9f665b4)

**Comment by devikrishnamk0123** [comment]
> I think I've commented this elsewhere already, but can you reproduce this with all tasks or only a specific task? Which attributes does the task have? Are you able to reproduce this on [try](https://try.vikunja.io)?

There is no option to import from trello in [try](https://try.vikunja.io/) :-(

**Comment by kolaente** [comment]
Are you able to reproduce this when the project has a background vs when it does not have one? 

Might be related to https://kolaente.dev/vikunja/vikunja/issues/2246

**Comment by kolaente** [comment]
I've pushed a potential fix for this in https://github.com/go-vikunja/vikunja/commit/0bc9a670d729f75fd653984aafdf0a37c67a2d8d. Can you check with the latest unstable build if the problem still exists?

**Comment by simeoncode** [comment]
I've pulled `:latest` and according to some clicking around, the issue is now resolved 👍

**Comment by kolaente** [comment]
`latest` is the last release, which does not have the fix (nor the bug). You'll want to check with `unstable`. [Check out the docs](https://vikunja.io/docs/versions/) for more info about the versions.

**Comment by simeoncode** [comment]
It was a typo. I meant `:unstable`, of course.
