### ISSUE TITLE
After deleting the done bucket, no task in the project can be done

### ISSUE THREAD

**Issue by onichandame** [go-vikunja/vikunja#234]
### Description

![image](https://github.com/go-vikunja/vikunja/assets/23728505/5b106b71-f5fc-47b1-92c7-15f2b9e68d32)
I created a bucket in a project, mark it as the done bucket. then delete the bucket. now I cannot mark any task in the project as done. the logged error message is shown above. the user interface is bugged as well.

After digging the database, I see that the `done_bucket_id` column in projects is not cleared after deleting the bucket. However I don't have an idea how it can be fixed as I am new to the codebase.

### Vikunja Version

0.23.0

### Can you reproduce the bug on the Vikunja demo site?

Yes

### Screenshots

https://github.com/go-vikunja/vikunja/assets/23728505/7e9ef647-5faa-4ea7-919b-019d8692fd72

I keep clicking 'mark as done' button but nothing happens

**Comment by onichandame** [comment]
@kolaente Thx! I can confirm that it is fixed on the demo site. in which stable version will the fix be released?

**Comment by kolaente** [comment]
In the next release, coming in a few weeks.
