### ISSUE TITLE
Integration microsoft to do list import function does not import 

### ISSUE THREAD

**Issue by inuonly** [go-vikunja/vikunja#238]
### Description

The import option in menu leads to a page where microsoft to do list can be imported, once the process completes we are greeted with a successful message and are informed that it will happen in background and we will notify. Even after days we still dont se any list imported from microsoft to do. Same is applid to trello just to check but it still is not working. It never fails both methods microsoft to do and trello are completing successfully. But nothign is imported.

### Vikunja Version

Version: v0.23.0

### Browser and version

123.0.1 (64-bit)

### Can you reproduce the bug on the Vikunja demo site?

No

### Screenshots

Vikunja Version :
![image](https://github.com/go-vikunja/vikunja/assets/26686197/a33d78e7-5398-4edd-962e-37e4ce8947e7)
Browser Version :
![image](https://github.com/go-vikunja/vikunja/assets/26686197/6ee8074d-54bc-4ee3-bc5e-1310b731b237)

Steps : 
1. Import page options: 
![image](https://github.com/go-vikunja/vikunja/assets/26686197/7a415dae-bdcf-4eaa-a016-8d181e3a0159)
2. individual microsoft to do import page 
![image](https://github.com/go-vikunja/vikunja/assets/26686197/ff5a7379-a910-4042-ab30-dd945e093870)
3. microsoft login page 
![image](https://github.com/go-vikunja/vikunja/assets/26686197/c6e064a3-cd63-4cf0-9bfc-9addce2e12db)
4. redirected back to result page in vikunja after logging in
![image](https://github.com/go-vikunja/vikunja/assets/26686197/b1ea2407-ca26-45c9-8708-8ab9416358b1)

**Comment by kolaente** [comment]
What do you see in the logs?

**Comment by kolaente** [comment]
If you search the log for Error, do you see anything?

**Comment by kolaente** [comment]
>  This is the log , after changing to debug level now.

This looks like the import did not actually start - did it tell you "you already did the import once, do you really want to do this again?" - in that case you need to confirm the import.
The debug log should give you plenty of information while the import is running.

**Comment by kolaente** [comment]
Okay, then that's the bug. I'll take a look.

**Comment by kolaente** [comment]
I'm heading off on vacation tomorrow for a week, will ping you back after that when I find something.

**Comment by kolaente** [comment]
The message not showing is fixed in https://github.com/go-vikunja/vikunja/commit/0b9ef27d04f388b86acad854ad118c870fead02a. Please check with the next unstable build (should be ready for deployment in ~45min, also on [try](https://try.vikunja.io)).

**Comment by kolaente** [comment]
Unstable builds are built from the latest commit in the main branch. In irregular intervals a release is made from that and then the changes will be cut into a release. In your case, that means you can keep using unstable and then switch to the next release once that's out.
