### ISSUE TITLE
No ipv4 listening on new install

### ISSUE THREAD

**Issue by jwynn6** [go-vikunja/vikunja#239]
### Description

Implementing exactly the traefik v2 example docker-compose, there is no listening port opened for ipv4. Modifying the VIKUNJA_SERVICE_INTERFACE to listen on 0.0.0.0:3456 has no effect either. Modifying it to listen on other ipv4 addresses (127.0.0.1:3456) does work however.  

### Vikunja Version

0.23 and unstable were both tested against

### Can you reproduce the bug on the Vikunja demo site?

No

**Comment by kolaente** [comment]
I was unable to reproduce this, it seems to work fine. The web interface listens on all adapters by default.

If you inspect the container, what IPs do you get? Does it work if you curl them on port `3456`?

**Comment by kolaente** [comment]
Closing as inactive, please ping or open a new issue with relevant information if you still have this problem.
