### ISSUE TITLE
Opera Mobile OIDC Login not possible

### ISSUE THREAD

**Issue by GoliathLabs** [go-vikunja/vikunja#243]
### Description

Hi there,
We've moved from Trello to Vikunja and like it a lot. The only problem is that some members of our organisation use Opera Mobile on their smartphones. It doesn't seem to work as expected as the "Login with Authentik" button seems to be missing on their end. With Chrome, Firefox, etc. it works just fine.

There's nothing unusual in the logs.

### Vikunja Version

sha256-bf11fe9c8a41483559260a7828cf810c714b2a6366cc1b6c9ada37cd4ada735e

### Browser and version

Opera Mobile (latest version as of today)

### Can you reproduce the bug on the Vikunja demo site?

No

### Screenshots

![Screenshot_2024-03-26-14-48-42-734_com opera browser](https://github.com/go-vikunja/vikunja/assets/8057646/92f09b00-d4ff-4a93-8422-1e965af58224)

**Comment by kolaente** [comment]
What's that version string from?

**Comment by GoliathLabs** [comment]
It's the hash of the docker image used from docker hub

**Comment by kolaente** [comment]
Which version does it resolve to? You can view that in the about dialog in the frontend, reachable when you click on the arrow next to your profile picture on the top right.

**Comment by kolaente** [comment]
Do you see the login button when you go to https://app.vikunja.cloud ?

**Comment by GoliathLabs** [comment]
Yes, they see the login button. Apparently login does work. But they get to the blank page above after logging in via OIDC

**Comment by GoliathLabs** [comment]
> I'm unable to reproduce this. What does the URL look like, after they get redirected from the openid provider?

I updated vikunja to the latest unstable release a few days ago. I can't reproduce it either. I'll ask the person in the team to show me if the problem still exists, until then I'll close this issue as resolved.

Thank you very much for your time :)
