### ISSUE TITLE
cannot scroll sidebar to switch to different list items

### ISSUE THREAD

**Issue by inuonly** [go-vikunja/vikunja#249]
### Description

demo vikunja site screenshot showing list extends screen but no scroll bar shows up to scroll down to select list items

My instance is docker with unstable tag . Version: v0.23.0+482-bc19a2fb78
Same is also applicable to demo site, in fact screenshot is from demo site.

I found a way to get scrollbar back but not sure if this is what is required to fix. 
I inspected the webpage an selected this element as shown in the image : 
![image](https://github.com/go-vikunja/vikunja/assets/26686197/4ce37bd5-58b4-43f6-94bb-630fd40faa0e)
And then I simply added `overflow-y:scroll;` to the aside element as show in the image to fix it temporarily:
![image](https://github.com/go-vikunja/vikunja/assets/26686197/aed7482c-6f75-435d-868b-6d1cc54b530f)

### Vikunja Version

Version: v0.23.0+482-bc19a2fb78

### Browser and version

Firefox Browser 124.0.2 

### Can you reproduce the bug on the Vikunja demo site?

Yes

### Screenshots

Browser Version : 
![image](https://github.com/go-vikunja/vikunja/assets/26686197/3ff8a3f3-ab90-4e7d-ae10-2c87d25d6e15)
Vikunja Version :
![image](https://github.com/go-vikunja/vikunja/assets/26686197/49b4c821-69b4-4893-adbc-37eab6bb0acd)
Demo Site no scrollbar for sidebar :
![image](https://github.com/go-vikunja/vikunja/assets/26686197/70d2ffad-f0ef-4bd9-beb0-65d4628775e6)
Element that needs overflow-y: scroll to be added in order to get scroll bar back 
![image](https://github.com/go-vikunja/vikunja/assets/26686197/4ce37bd5-58b4-43f6-94bb-630fd40faa0e)
Screenshot showing temporary fix using overflow-y:scroll method for aside element as explained in description:
![image](https://github.com/go-vikunja/vikunja/assets/26686197/3181f405-03da-4178-8f60-b041bdc32dad)

**Comment by kolaente** [comment]
Should be fixed in https://github.com/go-vikunja/vikunja/commit/ed4be389ab6fc1691c9053cfc2d620ffe70ecc40, please check with the next unstable build (should be ready for deployment in ~45min, also on [try](https://try.vikunja.io)).
