### ISSUE TITLE
Line breaks not working in task description

### ISSUE THREAD

**Issue by filcuk** [go-vikunja/vikunja#250]
### Description

It is not possible to insert line break in task description using shift+enter (nothing happens).
Pasting text with line breaks seems to convert those to paragraphs.
Line breaks should have no gap between lines.

### Vikunja Version

v0.23.0

### Can you reproduce the bug on the Vikunja demo site?

Yes

### Screenshots

![image](https://github.com/go-vikunja/vikunja/assets/1339532/651cff2b-d424-4370-8545-8dbea52bdda6)
![image](https://github.com/go-vikunja/vikunja/assets/1339532/86768f27-8aeb-4bba-ae21-926f386eee83)

Thanks for your consideration.

**Comment by kolaente** [comment]
Fixed in 3e7225ebee2fda6e9d30b4911537304da7f80fb9, please check with the next unstable build (should be ready for deployment in ~45min, also on [try](https://try.vikunja.io)).
