### ISSUE TITLE
Saved filters are not updated when tasks are updated

### ISSUE THREAD

**Issue by mvalois** [go-vikunja/vikunja#255]
### Description

When creating a saved filter to get tasks for a given user, shown tasks are not updated until we edit their description. For instance, when removing the assignee from the task, it still appears in the list of the saved filter.

### Vikunja Version

0.22.1

### Browser and version

Firefox last version, reproducible using debian desktop client

### Can you reproduce the bug on the Vikunja demo site?

No

**Comment by kolaente** [comment]
Please upgrade your instance to 0.23.0 or the last unstable build. 0.22.1 is not supported anymore.

**Comment by mvalois** [comment]
Even after upgrading both the server and client to 0.23.0 the issue still appears.

**Comment by kolaente** [comment]
Does it work with the latest unstable build? (make a backup before upgrading!) Are you using Typesense?

**Comment by mvalois** [comment]
yes we are using typesense.

**Comment by mvalois** [comment]
Disabling typesense resolves the issue.

**Comment by kolaente** [comment]
This should be fixed in COMMIT, please check with the next unstable build (should be ready for deployment in ~45min).

You'll need to do a full reindex via the `vikunja index` cli command.
