### ISSUE TITLE
Switching back from :unstable tag to :latest tag breaks website 

### ISSUE THREAD

**Issue by inuonly** [go-vikunja/vikunja#257]
### Description

Earlier to test one of the UI issues which was resolves by one of the vikunja team members, we switched from latest tag in docker image to unstable tag
![image](https://github.com/go-vikunja/vikunja/assets/26686197/365ba3a1-c688-4a5e-96cd-04deee64424b)

Now the change has been added to latest (stable version) so we wanted to switch back. But if change unstable tag to latest, the site breaks following some UI error messages as shown in screenshots below. 

We are unable to see any list contents if we click on any list items. 
Is there anything else that needs to be taken care of before switching or am I doing this wrong way.  Adding some referenc epoint logs.
Steps : 
  - when the container is started ![image](https://github.com/go-vikunja/vikunja/assets/26686197/dd92976c-9939-4cce-92c9-54c5384d5472)
  - few moments later ![image](https://github.com/go-vikunja/vikunja/assets/26686197/6bb66934-6f3b-4132-9449-cde47b496c73)
  - when we click any list 
    ![image](https://github.com/go-vikunja/vikunja/assets/26686197/ca6cbcb1-4e9b-463e-a168-92c52dd06f70)
  - log error after we click any list item in UI 
![image](https://github.com/go-vikunja/vikunja/assets/26686197/a24c0759-f309-471c-8161-ee4899cc3025)

Observations : 
1. This affects overview, upcoming, and any list item, either not loading or loads with same error as above (internal server error) in UI.
2. However the projects list is still loading. I believe this is only occuring when trying to fetch list items. 
3. We can see in error log that same error is repeating but with different code as shown in following images.     
![image](https://github.com/go-vikunja/vikunja/assets/26686197/eb792b83-f89e-49d6-924d-f7a403107c51)
![image](https://github.com/go-vikunja/vikunja/assets/26686197/e89c5eb0-5076-4184-bdad-e9a5ae90947a)
![image](https://github.com/go-vikunja/vikunja/assets/26686197/211861e4-0bab-4659-92eb-ada224800b5b)

Note: 
We are using microsoft todo integration which might be an extra step than standard installation. Ref : #238 
This was fixed and was working. So hopefully this does not add overhead to look for error but including this to be on same page for setup. 
* In logs screenshot we have just removed IP address information. Rest is as is.
Hope this info helps. 
Thanks in advance. 

### Vikunja Version

v0.23.0+577-fd126fa234

### Browser and version

Firefox 125.0.2 (64-bit) 

### Can you reproduce the bug on the Vikunja demo site?

No

### Screenshots

Viknuja Version : 
![image](https://github.com/go-vikunja/vikunja/assets/26686197/03b6cede-2f97-47a1-ac9a-5be2e5723b95)

Browser Version : 
![image](https://github.com/go-vikunja/vikunja/assets/26686197/e857b561-943d-4a88-8a85-9258914529a7)

Changes Made : 
![image](https://github.com/go-vikunja/vikunja/assets/26686197/365ba3a1-c688-4a5e-96cd-04deee64424b)

Errors: 
  - ![image](https://github.com/go-vikunja/vikunja/assets/26686197/ca6cbcb1-4e9b-463e-a168-92c52dd06f70)
  - ![image](https://github.com/go-vikunja/vikunja/assets/26686197/7aae6326-82a4-4f8d-8927-05243e715170)
  - ![image](https://github.com/go-vikunja/vikunja/assets/26686197/a24c0759-f309-471c-8161-ee4899cc3025)
  - ![image](https://github.com/go-vikunja/vikunja/assets/26686197/eb792b83-f89e-49d6-924d-f7a403107c51)
  - ![image](https://github.com/go-vikunja/vikunja/assets/26686197/e89c5eb0-5076-4184-bdad-e9a5ae90947a)
  - ![image](https://github.com/go-vikunja/vikunja/assets/26686197/211861e4-0bab-4659-92eb-ada224800b5b)

**Comment by kolaente** [comment]
When did you switch? From 0.23.0 to the version you listed?

**Comment by kolaente** [comment]
Downgrading is generally not supported. You can only switch to the next stable release or newer unstable builds once you've switched to unstable.
To switch from your unstable installation to a stable version you need to wait for the next release (0.24) and then upgrade from unstable to that.

You have two options now:

1. Roll back to 0.23.0 and restore from the last backup you have on that version
2. Stay on unstable until 0.24.0 is released.

If you only want to check things with an unstable build, you should either make the switch generally or make a backup, upgrade to unstable, check whatever you want to check, then go back to the last release and restore from backup.
