### ISSUE TITLE
Error when paste text to task - error reading 'nodeSize'

### ISSUE THREAD

**Issue by Marenostrum81** [go-vikunja/vikunja#259]
### Description

**Description**

When I try to paste text with external links, nothing is pasted. If I paste without formatting (ctrl+shift+V), then it does stick, but it doesn't look good because it loses the links and the highlighted text. 
When checking the console, the error `'Cannot read properties of undefined (reading 'nodeSize')' index.js 87`
 
After analyzing why some links seem to work and others, I find that if the text includes a link like this, it doesn't work:
`<a class="external" href="https://www.europeana.eu/es/search?page=1&amp;view=grid&amp;query=women%20in%20trade%20union%201850" target="_blank"><span>segundo enlace.</span><span class="external_link_icon" role="presentation"><span class="screenreader-only">Links to an external site.</span></span></a>`

But with this one, it works: 
`<a class="inline_disabled external" href="https://www.europeana.eu/es" target="_blank" rel="noreferrer noopener"><span>Europeana</span><span class="external_link_icon" style="margin-inline-start: 5px; display: inline-block; text-indent: initial; " role="presentation"><svg viewBox="0 0 1920 1920" xmlns="http://www.w3.org/2000/svg" style="width:1em; height:1em; vertical-align:middle; fill:currentColor">
    <path d="M1226.667 267c88.213 0 160 71.787 160 160v426.667H1280v-160H106.667v800C106.667 1523 130.56 1547 160 1547h1066.667c29.44 0 53.333-24 53.333-53.333v-213.334h106.667v213.334c0 88.213-71.787 160-160 160H160c-88.213 0-160-71.787-160-160V427c0-88.213 71.787-160 160-160Zm357.706 442.293 320 320c20.8 20.8 20.8 54.614 0 75.414l-320 320-75.413-75.414 228.907-228.906H906.613V1013.72h831.254L1508.96 784.707l75.413-75.414Zm-357.706-335.626H160c-29.44 0-53.333 24-53.333 53.333v160H1280V427c0-29.333-23.893-53.333-53.333-53.333Z" fill-rule="evenodd"></path>
</svg>
<span class="screenreader-only">Links to an external site.</span></span></a>`

Same browser, same extensions, but in self-host I'm having this issue, and the demo works correctly.

### Vikunja Version

0.23.0

### Browser and version

Edge, version 124.0.2478.51 (Compilación oficial) (64 bits)

### Can you reproduce the bug on the Vikunja demo site?

No

### Screenshots

![image](https://github.com/go-vikunja/vikunja/assets/4191154/0d927623-a2af-4632-a899-a1b42a17047c)

**Comment by kolaente** [comment]
If it works in the demo, it is likely already fixed (the demo always runs the latest commit from the main branch). Can you reproduce this on your installation with an unstable build? (Make a backup first, rollback is not supported)

**Comment by Marenostrum81** [comment]
I can confirm the unstable version (version 9 may) fixes this issue.
