### ISSUE TITLE
Unable to go to cloud app in Brave Private tab.

### ISSUE THREAD

**Issue by eric29** [go-vikunja/vikunja#260]
### Description

Login to cloud at vikunja.cloud/login. Then click on the "Open Vikunja" button. It'll redirect you to the cloud app, but then gets stuck on the "Welcome Back!" Llama page, with no way to proceed to the app.

Unsure if the issue is on the demo site since it doesn't use the same login process.

### Vikunja Version

Cloud version

### Browser and version

Brave Version 1.65.126 Chromium: 124.0.6367.118 (Official Build) (64-bit)

### Can you reproduce the bug on the Vikunja demo site?

No

### Screenshots

![image](https://github.com/go-vikunja/vikunja/assets/11360962/bf560021-a6ab-4db8-90c0-062bb67b720c)

**Comment by kolaente** [comment]
I'm unable to reproduce this using Brave `Version 1.65.122 Chromium: 124.0.6367.82 (Official Build) (64-bit)` (pretty much the same version as the one you've used)

When you got redirect to the page in the screenshot, what does the url look like?

**Comment by kolaente** [comment]
Closing as inactive, please ping or open a new issue with relevant information if you still have this problem.
