### ISSUE TITLE
Make import page have formatting consistent with other pages

### ISSUE THREAD

**Issue by RayBB** [go-vikunja/vikunja#264]
### Description

Right now the import page is quite strange and takes you out of the settings.

### Vikunja Version

Version: v0.23.0

### Can you reproduce the bug on the Vikunja demo site?

Yes

### Screenshots

| Image 1 | Image 2 |
|---------|---------|
|![image](https://github.com/go-vikunja/vikunja/assets/921217/3cafe7c1-9ad9-46ef-be70-dcd22ead3d44) |![image](https://github.com/go-vikunja/vikunja/assets/921217/864d8957-37b3-4e37-99b7-f9c7790cce8e) |

**Comment by kolaente** [comment]
What do you have in mind for the design?

**Comment by RayBB** [comment]
@kolaente It could be in the same template as the rest of the settings. Something like this:
<img width="1205" alt="image" src="https://github.com/go-vikunja/vikunja/assets/921217/9daef01e-e409-45fc-b9fc-b46f616925b8">

**Comment by kolaente** [comment]
This has been implementedrecently, please check with the next unstable build (should be ready for deployment in ~45min, also on [try](https://try.vikunja.io)).
