### ISSUE TITLE
Sorting by due date

### ISSUE THREAD

**Issue by sergue2** [go-vikunja/vikunja#270]
### Description

In the table view there seems to be an option to sort by expiry date.
Unfortunately, no sorting is performed.

### Vikunja Version

v0.23.0

### Browser and version

Firefox, Chrome and Desktop App

### Can you reproduce the bug on the Vikunja demo site?

Yes

### Screenshots

![grafik](https://github.com/go-vikunja/vikunja/assets/80391307/c69801a0-d543-4597-99c6-fd5802453e4a)

**Comment by kolaente** [comment]
By default, the ID is selected for sorting. If you do not unselect it, it will try to sort by the id first and then by due date. Can you confirm that you only have due date selected?

**Comment by sergue2** [comment]
oh, that's right.
My bad....
I'm sorry!
