### ISSUE TITLE
Add Permalinks to Comments

### ISSUE THREAD

**Issue by devadattas** [go-vikunja/vikunja#272]
**Description:**

We need to add the functionality of permalinks to comments within the Vikunja application. This will allow users to directly link to specific comments, enhancing the usability and navigation of the comment section. 

**Acceptance Criteria:**
1. Each comment should have a unique permalink.
2. The permalink should be easily accessible from the comment interface (e.g., a link icon next to each comment).
3. Clicking on a permalink should navigate the user directly to the corresponding comment, highlighting it or bringing it into view.
4. Permalinks should be shareable and retain functionality across different devices and sessions.

**Technical Notes:**
- Ensure the permalink format is consistent with Vikunja's existing URL structure.
- Update the comment component to include the permalink feature.
- Test for cross-browser compatibility and responsiveness.

**Additional Information:**
This feature request stems from user feedback indicating the difficulty in referencing specific comments in long threads. Implementing permalinks will significantly improve the user experience.

**Comment by kolaente** [comment]
I've added an item to the backlog about this - for the web version.

**Comment by devadattas** [comment]
Isn't this https://github.com/go-vikunja/vikunja a mirror for https://kolaente.dev/vikunja/vikunja ?

**Comment by kolaente** [comment]
Yes.

**Comment by devadattas** [comment]
Wondering if I could add PRs to this repository?

**Comment by kolaente** [comment]
You mean here on GitHub? That is not possible unfortunately because the CI runs only on the Gitea instance. You can send a PR there.

Also check out [our contribution guidelines](https://vikunja.io/docs/development/).

**Comment by devadattas** [comment]
I have tried logging into https://kolaente.dev/vikunja/vikunja

But it won't let me login.

![image](https://github.com/go-vikunja/vikunja/assets/56180/b9fa9dbf-ea41-42c0-ac9c-6ff379644e7a)

**Comment by kolaente** [comment]
I've enabled your account, you should be able to send a PR now.

We have a spam problem on the Gitea instance and the only thing which really works is manually enabling accounts.

**Comment by devadattas** [comment]
You said:

https://github.com/go-vikunja/vikunja/issues/272#issuecomment-2165803796

    I've added an item to the backlog about this - for the web version.


Could you please point me to the ticket at https://kolaente.dev/ ?

**Comment by devadattas** [comment]
Please check https://kolaente.dev/vikunja/vikunja/issues/2441 and the corresponding PR at https://kolaente.dev/vikunja/vikunja/pulls/2442

**Comment by kolaente** [comment]
> Could you please point me to the ticket at https://kolaente.dev/ ?

There's no issue on the Gitea instance, but a task here: https://my.vikunja.cloud/tasks/20650#share-auth-token=UrdhKPqumxDXUbYpEGJLSIyNTwAnbBzVlwdDpRbv
