### ISSUE TITLE
Vikunja not requesting OIDC scope "vikunja_scope" even though it is specified in config

### ISSUE THREAD

**Issue by requ1Re** [go-vikunja/vikunja#273]
### Description

I am using OIDC SSO using authentik. I want to use the automatic team creation/syncing, but it does not seem to work.

I configured it in authentik and Vikunja as described [in the docs](https://vikunja.io/docs/openid/#automatically-assign-users-to-teams), but when I sign in, the application does not request the `vikunja_scope` scope, even though it is specified in the `config.yml`.

### Vikunja Version

v0.23.0

### Can you reproduce the bug on the Vikunja demo site?

No

### Screenshots

`config.yml`:
![image](https://github.com/go-vikunja/vikunja/assets/22103563/4c8204f9-6834-4f55-b842-4637d6e2bf7e)

What Vikunja requested:
![image](https://github.com/go-vikunja/vikunja/assets/22103563/81832d10-bb7e-42ca-910d-cfac408480c3)

**Comment by kolaente** [comment]
As stated in the docs you linked, the feature is only available from Vikunja 0.24.0, which has not been released yet.

**Comment by requ1Re** [comment]
Sorry, seem that I am indeed blind :)
