### ISSUE TITLE
Shared Task created by team member not in CalDav List

### ISSUE THREAD

**Issue by qroac** [go-vikunja/vikunja#275]
### Description

My wife and I just started using Vikunja.
On a shared project, my wife created a task.
I added caldav sync to DAVx on my android phone. The task created by my wife does not appear on my phone.
Tasks created by me appear as expected.

### Vikunja Version

v0.23.0

### Can you reproduce the bug on the Vikunja demo site?

No

**Comment by kolaente** [comment]
Can you verify DAVx performed a sync of the tasks?

**Comment by qroac** [comment]
Yes
I just created a new task in the same project. After manual sync in DAVx it appeard on my phone.
Do you plan to publish a new release in the next weeks?
I'm curious because I couldn't reproduce this on the demo instance. maybe it is already fixed.

**Comment by kolaente** [comment]
There have been a few fixes to the caldav implementation, yes. If all goes to plan, the next release will happen in this or one of the next weeks.

**Comment by kolaente** [comment]
Closing as resolved with one of the last releases, feel free to ping if you have other issues.
