### ISSUE TITLE
Task malformated when created via API 

### ISSUE THREAD

**Issue by BasselRawda** [go-vikunja/vikunja#278]
### Description

I am trying to create tasks from my nodejs app to my self-hosted Vikunja instance. When setting the description, the markdown characters and formatting are not being taken into account.
URL used: VIKUNJA_BASE_URL/projects/1/tasks
Description string:

let template = ## Bug Report Submission

      **Submitted By**:
      xxx (ID: 123)

      **User Requested**:
      yyy (ID: 123)

      **Submitted At**:
      ${new Date().toISOString()}

      **Description**: ${description}`;

      const data = {
        title: `${command}: ${subject}`,
        description: template,
        hex_color: "#D3D3D3",
      };

### Vikunja Version

v0.23.0

### Can you reproduce the bug on the Vikunja demo site?

No

**Comment by kolaente** [comment]
The frontend supports markdown shortcuts and pasting, but the api does not support it. You need to convert your markdown to html if you want to have it displayed with rich text in the web frontend.
