### ISSUE TITLE
Error "You must provide at least a task title" when creating a task with title ending in "y"

### ISSUE THREAD

**Issue by cortl** [go-vikunja/vikunja#282]
### Description

On Kanban view, click "+ Add Another Task" and type in "Monday" I see the error task requires a title. I have to delete the last character and re-submit to get it to go through. I see a PUT network request `/api/v1/projects/2/tasks` with 400 Bad request. The payload is missing "title" despite it being present in the UI.

I think it might have something to do with the task ending in "y"

### Vikunja Version

v0.24.0

### Browser and version

Brave

### Can you reproduce the bug on the Vikunja demo site?

Yes

**Comment by kolaente** [comment]
This is definitely a bug, but unrelated to the ending of the word. The quick add magic functionality detects "monday" and removes it from the title to set a due date of next Monday.
