### ISSUE TITLE
Cannot set "Saved filter used on the overview page"

### ISSUE THREAD

**Issue by bernardosulzbach** [go-vikunja/vikunja#284]
### Description

After I start typing into the control, I get a red box saying

> Error
> Cannot read properties of undefined (reading 'isArchived')

I think this will be easy to reproduce, as I have almost no custom settings (just disabled user registration).

I'm running the docker image using PostgreSQL for the database. 

### Vikunja Version

v0.24.0

### Can you reproduce the bug on the Vikunja demo site?

No

**Comment by kolaente** [comment]
I'm unable to reproduce this. Does it work for you on the demo?

**Comment by bernardosulzbach** [comment]
As I said, no, I can't reproduce it in the demo. The demo says it is v0.23.0-951-af54ee6c5c and with that version I can't find  "Saved filter used on the overview page" in the settings. Maybe it's not a version issue, maybe it's just disabled in the demo through an option? I'm using Chrome 126.0.6478.126 (Official Build) (64-bit).

**Comment by kolaente** [comment]
You need to create a filter before the option shows up in the settings.

**Comment by bernardosulzbach** [comment]
I just tested it with Firefox and it worked, so I chose a filter and saved my settings. Now it also seems to work on Chrome... I thought the problem maybe was that I had multiple filters with the same name but that doesn't seem to be it. Anyway, I will reopen with a reliable reproduction if I find a way to consistently trigger it.
