### ISSUE TITLE
Date query filters are hopelessly broken 

### ISSUE THREAD

**Issue by aboveagency** [go-vikunja/vikunja#286]
### Description

When creating a saved filter (really important for our project management) - there is no way to work with date filters. There isn't much documentation on the correct format for dates so we have to go by what the query wizards sets up for us. 

1. Start the query with startDate>=
2. Click on the equal sign to select a date 
3. Select a date so it displays
4. Click Created Saved Filter

![image](https://github.com/go-vikunja/vikunja/assets/126202827/bf4e4593-2e0a-4f88-9798-0909dcc6595a)

Tried many combinations / formats for date, spacing - variables. 

On the main Vikunja demo instance you receive  a different error, "invalid struct" 

I would suggest rolling back this update until things are smoother.

### Vikunja Version

v0.24.0

### Can you reproduce the bug on the Vikunja demo site?

Yes

**Comment by kolaente** [comment]
Probably the same as this: https://community.vikunja.io/t/filtering-unexpected-character-relative-dates/2544

Does it work if you wrap the date in `'`?

**Comment by kolaente** [comment]
Fixed in https://github.com/go-vikunja/vikunja/commit/70615d6843c7e6dc3bbbfdff82c82694b680129d, please check with the next unstable build (should be ready for deployment in ~45min, also on [try](https://try.vikunja.io)).
