### ISSUE TITLE
OAuth with self-signed certificate

### ISSUE THREAD

**Issue by 3isenHeiM** [go-vikunja/vikunja#287]
### Description

Hi, I'm using Vikunja with Autnetik as SSO provider. Both are running on the same machine, with self-signed certificates to each.

Apparently the SSO (Authentik) must have a signed certificate, because I'm getting this error : 
```log
vikunja-server  | 2024-07-18T13:42:33.280188937Z: ERROR ▶ openid/GetAllProviders 0e1 Error while getting openid provider authentik Login: Get "https://auth.<FQDN>/application/o/vikunja/.well-known/openid-configuration": tls: failed to verify certificate: x509: certificate signed by unknown authority
```

How can I circumvent this ? I haven't found a flag in the configfile to skip the TLS vertificate verification...

Thanks !

### Vikunja Version

v0.24.0

### Can you reproduce the bug on the Vikunja demo site?

Please select

**Comment by kolaente** [comment]
There is no option in Vikunja to disable certificate validation. You should add the root CA of your self-signed certificate to the trust store on your OS and then mount it into the docker container (From the log message, it looks like you're using docker, if not you don't need to mount it) into one of [these locations](https://go.dev/src/crypto/x509/root_linux.go).

Another option would be Let's Encrypt.

**Comment by 3isenHeiM** [comment]
Thanks for the hint ;)

I indeed mounted my custom CA certificate in `/etc/ssl/certs/<ca-cert.pem>` in the docker compose file, and it solved the issue.
