### ISSUE TITLE
Saved Filter on Overview Page Not Working

### ISSUE THREAD

**Issue by saucedge** [go-vikunja/vikunja#289]
### Description

Hello, thanks for an awesome project!

I'm seeing an issue trying to apply a Saved Filter to my Overview page.  The filter string is "done = false && project in Project3, Project4, Project5".  Actually, as a side note, I'd prefer my filter be "done = false && project != Project1 && project != Project2" but that throws an error (not trying to address that now).  When I view the filter directly by selecting it, all of the issues appear as expected.  But, when I select the filter as "Saved filter used on the overview page" in settings, the overview page shows "Nothing to do — Have a nice day!" where I would expect it to show the same tasks that appear in the filter.  

### Vikunja Version

Version: v0.24.1

### Browser and version

Chrome Version 126.0.6478.127

### Can you reproduce the bug on the Vikunja demo site?

Yes

**Comment by mvalois** [comment]
Got the same since 0.24.0, still in 0.24.1. Tell me if you need dumps.
Keep going on your great work!
Cheers!

**Comment by GTHeyyy** [comment]
Hi!
Same here on fresh install

**Comment by greyivy** [comment]
Not working for me, either. Also on 0.24.1.

**Comment by kolaente** [comment]
Fixed in https://github.com/go-vikunja/vikunja/commit/97e030a1fc032c73ca6144139a488c18979fb310, please check with the next unstable build (should be ready for deployment in ~45min, also on [try](https://try.vikunja.io)).
