### ISSUE TITLE
Can not order tasks in table view

### ISSUE THREAD

**Issue by latenssi** [go-vikunja/vikunja#292]
### Description

In a projects table view there are these carret buttons for column headers that suggest one could order the tasks by that particular column. However pressing these buttons does nothing to the tasks, only adjusts the button rendering.

### Vikunja Version

0.24.1

### Can you reproduce the bug on the Vikunja demo site?

Yes

### Screenshots

![image](https://github.com/user-attachments/assets/31ece56e-2386-489e-966a-edede0f7dc09)

**Comment by kolaente** [comment]
You need to unselect sorting by task number first (the first column). In your screenshot, you're sorting by number and then the other fields.
