### ISSUE TITLE
Tasks repeated when creating a duplicate of a project

### ISSUE THREAD

**Issue by cbnathanael** [go-vikunja/vikunja#297]
### Description

When creating a duplicate of a project, all of the child tasks appear twice. Refreshing the page does not remove the doubled tasks. However, making a change to one, like re-ordering it will remove the duplicate after refresh, but other untouched tasks remain doubled. 

Steps to reproduce:
1. Create a new project, add several tasks
![Screenshot 2024-07-27 at 12-51-20 duplicate bug test Vikunja](https://github.com/user-attachments/assets/ebbf18ba-97a3-45d0-bc44-ff7a54ec2eb2)

2. Using the 3-dot menu (either from the project title in the header, or from the project list in the side bar) select duplicate. No parent project is required. Notice the doubled task list
![image](https://github.com/user-attachments/assets/b335f733-e408-4b63-ad6c-f3be5fe8dec3)

3. Inspecting the task links, they have the same ID 
![image](https://github.com/user-attachments/assets/7b75ecbd-4a91-452b-8f86-e53b50b91471)

4. Refreshing the page does not remove the duplicates. Reorder a single item and refresh the page. Notice how the altered task is now gone
[Screen recording of this behavior](https://github.com/user-attachments/assets/aa788dbf-eb64-47b5-aa40-9fdfe971d1be)

### Vikunja Version

0.24.1

### Browser and version

Firefox 128.0.3, Chrome 127.0.6533.73

### Can you reproduce the bug on the Vikunja demo site?

Yes

**Comment by kolaente** [comment]
Do the duplicate tasks disappear when you create a new view?

**Comment by cbnathanael** [comment]
I created a new list view, and they were not duplicated there, but the original/default still showed the duplicates.

**Comment by kolaente** [comment]
Fixed in https://github.com/go-vikunja/vikunja/commit/b83448b7a6d78fea07e3e88af45a468b7d5b968b, please check with the next unstable build (should be ready for deployment in ~45min, also on [try](https://try.vikunja.io)).
