### ISSUE TITLE
after the update to 24.1 all my project are empty without any tasks

### ISSUE THREAD

**Issue by intellekta** [go-vikunja/vikunja#299]
### Description

my system is yunohost 0.24.1~ynh1
after the update from 22.1 all my project are empty without any tasks 
overview shows some tasks
the user about info in the browser shows the old Version: v0.22.1
is it possible that the api 22 is not compatible with 24?
is there an seperate API/Frontend update to 24?
thanks in advance

### Vikunja Version

24.1

### Browser and version

last chrome and vivaldi

### Can you reproduce the bug on the Vikunja demo site?

No

### Screenshots

On the demo site the user about shows 24.1 on my site user about shows 22.1

**Comment by dpschen** [comment]
Maybe this helps:

https://vikunja.io/changelog/whats-new-in-vikunja-0.23.0#api-frontend-and-desktop-are-now-merged-in-one-repo

**Comment by intellekta** [comment]
Thanks, a Yunohost member has fixed it with a newer update.
https://github.com/YunoHost-Apps/vikunja_ynh/issues/70
