### ISSUE TITLE
Documentation on todoist migration in the sample config is contradicting

### ISSUE THREAD

**Issue by wucke13** [go-vikunja/vikunja#302]
### Description

# Description

The config contains the following statements on the `migration.todoist.redirecturl`:

1. The url where clients are redirected after they authorized Vikunja to access their todoist items.
2. This needs to match the url you entered when registering your Vikunja instance at todoist.
3. This is usually the frontend url where the frontend then makes a request to /migration/todoist/migrate with the code obtained from the todoist api.
4. Note that the Vikunja frontend expects this to be /migrate/todoist

Now the information that can be deferred from it.

a. From statement 1. I can derive that this is the URL where clients are redirected to after they authorized in Todoist. Todoist calls this `OAuth redirect URL` (which precisely controls where Todoist redirects the user after they click `authorize`).
b. From statement 2. I can derive, that this must be equal to the URL that I register with, which Todoist calls the `App Service URL` (see first screenshot, this is the only URL asked during registration).
c. Statement 3. tells me that this URL must somehow cause the (Vikunja?) frontend to request /`migration/todoist/migrate`. So I would expect that there is some url, that when accessed, causes the frontend itself to make a request to `migration/todoist/migrate`.
d. Statement 4. tells me, that this URL is expected to be `/migrate/todoist`.

From as per a. and b. we can derive that both `OAuth redirect URL` and `App Service URL`  must have the same value, and as per d. we know that this value must be `/migrate/todoist`.
Now c. tells us that when accessing `/migrate/todois` the frontend (?) will cause a request to `migration/todoist/migrate`. However, that is not happening, instead I land on `https://vikunja.wucke13.de/migrate/todoist?code=<redacted>&state=<redacted>` showing me `Not found`.

![image](https://github.com/user-attachments/assets/09902652-06d7-4077-a402-aacf049b2196)

# Questions

- Why mention `/migration/todoist/migrate` if it is not relevant for the setting (as per statement 4., `/migrate/todoist`) is what the user needs to know.
- Do `OAuth redirect URL` and `App Service URL` really both have to be `https://vikunja.example/migrate/todoist`?
- Do I correctly parse statement 3. as "There is some URL that when accessed with both the code/state get query parameters returne from Todoist's OAuth then internally requests `/`migration/todoist/migrate` that triggers the import", and hence "one has to insert this URL as `OAuth redirect URL` in the Todoist App Settings?

# Relevant snippet from the sample config
https://github.com/go-vikunja/vikunja/blob/bf1c8c6119648184a3d55f5653f4f49618b20578/config.yml.sample#L230-L234

### Vikunja Version

main/0.23.0 (Documentation that confuses me is on main branch, I run Vikunja 0.23.0)

### Can you reproduce the bug on the Vikunja demo site?

No

### Screenshots

# Workflow to failure

![image](https://github.com/user-attachments/assets/4b054abd-12d9-43ea-b15f-d480df660e32)

![image](https://github.com/user-attachments/assets/438c38ac-c892-4eff-b086-b696f9f621c6)

![image](https://github.com/user-attachments/assets/d9764c2f-ceb4-4f97-8ecb-7bf9ff6a7f33)

**Comment by dpschen** [comment]
I didn't work on the OAuth part, so can't help you in depth here, but maybe [this recent change of the frontend migration url](https://kolaente.dev/vikunja/vikunja/commit/eafd134be50c05317b8b86c1e798b2de1db0561f) has something to do with it.

**Comment by kolaente** [comment]
Clarified in https://github.com/go-vikunja/vikunja/commit/bf2d56c9d42d6beb023ac6ea4cc10c0db7e58a6c
