### ISSUE TITLE
Unable to Change Task Order in Safari

### ISSUE THREAD

**Issue by uyu423** [go-vikunja/vikunja#304]
### Description

In the Safari web browser, I am unable to change the order of created tasks (works fine in Chrome). When attempting to reorder tasks, it results in block selection instead, as shown in the attached screenshot. This issue is reproducible on the demo website.

### Vikunja Version

v0.24.1

### Browser and version

MacOS Safari version 17.5(19618.2.12.11.6)

### Can you reproduce the bug on the Vikunja demo site?

Yes

### Screenshots

![image](https://github.com/user-attachments/assets/ad0ee839-45b3-4f43-894d-5c1bcaecbce6)

![image](https://github.com/user-attachments/assets/5f2c2fe2-e1a6-405c-adfe-16f20357fd28)

**Comment by kolaente** [comment]
This has been reported elsewhere as well:

https://community.vikunja.io/t/task-re-ordering-is-not-working-in-safari/1916/4

https://kolaente.dev/vikunja/vikunja/issues/2092

**Comment by kolaente** [comment]
Fixed in https://github.com/go-vikunja/vikunja/commit/abf92e29facfa91a75fdce4ab04729010cb510f1, please check with the next unstable build (should be ready for deployment in ~45min, also on [try](https://try.vikunja.io)).
