### ISSUE TITLE
The gitea seems down

### ISSUE THREAD

**Issue by hugosxm** [go-vikunja/vikunja#305]
### Description

Hi, I saw that while trying to update the helm : 

```
helm upgrade --values custom-values.yaml vikunja vikunja/vikunja -n vikunja-app
Error: failed to fetch https://kolaente.dev/api/packages/vikunja/helm/vikunja-0.4.1.tgz : 500 Internal Server Error
```

Also if you go to : [https://kolaente.dev/vikunja/vikunja/issues](https://kolaente.dev/vikunja/vikunja/issues) you have 500 errors trying to open an issue. 

I think that gitea instance needs some love right now ^^. 

### Vikunja Version

0.4.1

### Can you reproduce the bug on the Vikunja demo site?

No

**Comment by kolaente** [comment]
Should work again.

**Comment by hugosxm** [comment]
Much better, thanks ! @kolaente
