### ISSUE TITLE
Feature request: Add opencontainer labels to Docker images 

### ISSUE THREAD

**Issue by RyanNgWH** [go-vikunja/vikunja#308]
### Description

It would be awesome if the Docker container images had opencontainers labels. I have seen this across multiple other containers and believe this is the standard for labeling images.

https://github.com/opencontainers/image-spec/blob/main/annotations.md

Doing a docker inspect on the current images shows only the label `"maintainer": "maintainers@vikunja.io"`. Adding labels such as `org.opencontainers.image.version` would be great. This will provide a way to obtain the current version of Vikunja from the running docker image which can be useful in automating the process of checking for updates.

Here is an example of the Jellyfin docker image with opencontainers labels:
```
"Labels": {
    "org.opencontainers.image.description": "The Free Software Media System",
    "org.opencontainers.image.documentation": "https://jellyfin.org/docs/",
    "org.opencontainers.image.source": "https://github.com/jellyfin/jellyfin",
    "org.opencontainers.image.title": "Jellyfin",
    "org.opencontainers.image.url": "https://jellyfin.org",
    "org.opencontainers.image.version": "10.9.8"
}
```

### Vikunja Version

0.24.0

### Can you reproduce the bug on the Vikunja demo site?

Yes

**Comment by kolaente** [comment]
Added in https://github.com/go-vikunja/vikunja/commit/07bd9de0c6515f8482f92519a4cf682ce297b263 - I did not find a way to set the version from the computed one in the magefile. Open for suggestions on how to do this.
