### ISSUE TITLE
Webhook task.updated not called when removing label

### ISSUE THREAD

**Issue by gdelfresno** [go-vikunja/vikunja#310]
### Description

When removing a label from a task, webhook `task.updated` is not triggered

Adding label works fine

I tried in the demo site and is happening the same https://try.vikunja.io/tasks/726 which has this webhook configured https://webhook-test.com/?address=5d99013d3e52cd943320dd3d8fc789e7

### Vikunja Version

0.24.2

### Can you reproduce the bug on the Vikunja demo site?

Yes

**Comment by kolaente** [comment]
Fixed in bea131cfd9dcf2c0bc726cf370c7ea2a5478b16a, please check with the next unstable build (should be ready for deployment in ~45min, also on [try](https://try.vikunja.io)).
