### ISSUE TITLE
Saving a project view throws error "G.update is not a function"

### ISSUE THREAD

**Issue by lynnerup** [go-vikunja/vikunja#312]
### Description

When saving any proejct view, the view is not saved, and you see an error saying "G.update is not a function".

As of writing, the error can be reproduced using "Project 1" in the demo site.

**How to reproduce**

1. Create a new project.
2. Go to the "Edit views" popup.
3. Click the edit button for any view
4. Click the Save button
5. The view is not saved, and you see an error saying "G.update is not a function".

### Vikunja Version

v0.24.1-43-ec2c2e74f0

### Browser and version

Google Chrome Version 127.0.6533.120 (Officiel version) (64-bit)

### Can you reproduce the bug on the Vikunja demo site?

Yes

### Screenshots

![image](https://github.com/user-attachments/assets/21cf3281-1852-4c83-8962-903ec5ead22b)

![image](https://github.com/user-attachments/assets/f7153e62-fbe3-464b-b998-de1fddaa4f05)

**Comment by JoaoVictorLouro** [comment]
I quickly looked into the source code, it looks like it was a simple typo. Its trying to update by calling update on a CLASS and not on the class instance. should be fixable by simply changing `ProjectViewService` to `projectViewService`.
Maybe i can open a PR...

<img width="533" alt="image" src="https://github.com/user-attachments/assets/16ebee2d-04e4-48be-9e52-02d0cf97a6a4">

**Comment by JoaoVictorLouro** [comment]
Here is the PR:
https://github.com/go-vikunja/vikunja/pull/318

Would be nice if someone could look into it!

**Comment by kolaente** [comment]
Fixed in https://github.com/go-vikunja/vikunja/commit/435cb2e7f753a1d8add6b4914890bf1ea93ab8c6, please check with the next unstable build (should be ready for deployment in ~45min, also on [try](https://try.vikunja.io)).
