### ISSUE TITLE
When having a Kanban board with bucket configuration mode "Filter", the first bucket is wrongly marked as the "done bucket"

### ISSUE THREAD

**Issue by lynnerup** [go-vikunja/vikunja#313]
### Description

If you create a Kanban view with configuration mode "Filter", then the first bucket will have the "done bucket" icon, even though the filter of the bucket is not related to this. Since you can configure your buckets in many different ways, is is probably best to not show the "done bucket" icon, when using filtered buckets.

As of writing, the error can be reproduced using "Project 1" and view "Kanban 2" in the demo site.

**How to reproduce**

1. Create a new project
2. Create a new view of type "Kanban" and "Filter"
3. Create a few buckets, for example one with filter "dueDate >= now" and one with filter "dueDate < now".
4. In the UI, you can see that the first bucket appear to be a "done bucket".

### Vikunja Version

v0.24.1-43-ec2c2e74f0

### Browser and version

Google Chrome Version 127.0.6533.120 (Officiel version) (64-bit)

### Can you reproduce the bug on the Vikunja demo site?

Yes

### Screenshots

![image](https://github.com/user-attachments/assets/368ec039-f060-412a-aa60-fdf807101071)
![image](https://github.com/user-attachments/assets/ff632df8-0cea-45b1-8caf-00df7c7df109)

**Comment by kolaente** [comment]
Fixed in https://github.com/go-vikunja/vikunja/commit/1a8f12ac137f20745895a5c3b828683324b82dc4, please check with the next unstable build (should be ready for deployment in ~45min, also on [try](https://try.vikunja.io)).
