### ISSUE TITLE
Saved Filter buckets only shows 25 items and throws error when scrolling to the bottom

### ISSUE THREAD

**Issue by lynnerup** [go-vikunja/vikunja#314]
### Description

I have Saved Filter, where I have created a Kanban board with bucket configuration mode "Filtered". The bucket shows all tasks with label "Ny". In the List view, I can see that there are 32 tasks with that label.
However in the Kanban board the bucket only shows 25 items. When I scroll to the bottom, I get the error "Cannot read properties of undefined (reading 'length')".

As of writing it can be reproduced in the demo site using the Saved Filter"View 1" and view "Kanban 2".

**How to reproduce**

1. Create a label called SomeTag
2. Create a project and add 30 tasks to the project, and add the label SomeTag to all the tasks.
3. Create a Saved Filter
4. Create a Kanban view with bucket configuration mode "Filter"
5. Create a bucket that shows tasks with label SomeTag
6. Open the view and scroll to the bottom.
7. You can see, that only 25 tasks are shows, and the error "Cannot read properties of undefined (reading 'length')" occurs.
8. 

### Vikunja Version

v0.24.1-43-ec2c2e74f0

### Browser and version

Google Chrome Version 127.0.6533.120 (Officiel version) (64-bit)

### Can you reproduce the bug on the Vikunja demo site?

Yes

### Screenshots

![image](https://github.com/user-attachments/assets/ce485344-6eee-4964-8f42-295f2b7ddcf6)
![image](https://github.com/user-attachments/assets/25968861-df96-4450-8844-351b828e29c0)
![image](https://github.com/user-attachments/assets/2b4adbe6-b77c-420c-9934-d432d23f558d)

**Comment by kolaente** [comment]
Fixed in 45ff5907e69b24f00926841790d0f4f3d11e530a, e4b541e6535885bf3e7b1b60f0f75f56aa43e3e4 and https://github.com/go-vikunja/vikunja/commit/1451f6e46f03c30384834ff99e0cbe7f15958536, please check with the next unstable build (should be ready for deployment in ~45min, also on [try](https://try.vikunja.io)).

**Comment by nische** [comment]
i have the same error with out labels. 
I used a save filter with manual created Buckets. If i scroll down i get the same error notification. 
Also the kanban dont safe if i move a task. But i think this is because of the error before(?)
