### ISSUE TITLE
Notification twice

### ISSUE THREAD

**Issue by wusa88** [go-vikunja/vikunja#316]
### Description

 Hello,

I have a small problem.
Every comment that is created is sent twice by e-mail.

Here is an example: 
![grafik](https://github.com/user-attachments/assets/31fb4c99-97b8-4928-91cb-9bc2c6250569)
![grafik](https://github.com/user-attachments/assets/8f4a636c-ce44-4836-bebe-97b76ba2a63f)

```
version: '3'

services:
  vikunja:
    image: vikunja/vikunja
    environment:
      VIKUNJA_SERVICE_JWTSECRET: password
      VIKUNJA_SERVICE_PUBLICURL: http://home.local/
      VIKUNJA_DATABASE_PATH: /db/vikunja.db
      VIKUNJA_SERVICE_ENABLETASKATTACHMENTS: 1
      VIKUNJA_SERVICE_ENABLEEMAILREMINDERS: 1
      VIKUNJA_MAILER_ENABLED: 1
      VIKUNJA_MAILER_AUTHTYPE: login
      VIKUNJA_MAILER_SKIPTLSVERIFY: 1
      VIKUNJA_MAILER_HOST: mail.home.local
      VIKUNJA_MAILER_PORT: 25
      VIKUNJA_MAILER_USERNAME: user
      VIKUNJA_MAILER_PASSWORD: password
      VIKUNJA_LOG_MAIL: stdout
      VIKUNJA_LOG_MAILLEVEL: DEBUG

    ports:
     - 3456:3456
    volumes:
     - /home/ubuntu/docker/vikunja/files:/app/vikunja/files
     - /home/ubuntu/docker/vikunja/db:/db
    restart: unless-stopped
```
Is this just a setting or is it a bug?
I am the owner of the project.
I tried with a team with me and my teammate. Both are admin's.
E-Mail is receiving twice.
If i try it without a team, just sharing with the person itself. Either read & write or admin, the e-mail is also receiving twice. 

Todays Mail Debug log. 
```
|2024-08-21T12:11:14.540697639Z: DEBUG|▶ [MAIL] 123 250 2.0.0 OK|
|---|---|
|2024-08-21T12:11:14.540790176Z: DEBUG|▶ [MAIL] 124 AUTH LOGIN|
|2024-08-21T12:11:14.54143637Z: DEBUG|▶ [MAIL] 125 334 VXMlcm5hbWU6|
|2024-08-21T12:11:14.541486052Z: DEBUG|▶ [MAIL] 126 YmFja2VwYWRt|
|2024-08-21T12:11:14.541988968Z: DEBUG|▶ [MAIL] 127 334 UGJzc3dvcmQ6|
|2024-08-21T12:11:14.542033301Z: DEBUG|▶ [MAIL] 128 YXdjNLIwMUM3|
|2024-08-21T12:11:14.605644044Z: DEBUG|▶ [MAIL] 129 235 2.7.0 Authentication successful|
|2024-08-21T12:11:14.605718375Z: DEBUG|▶ [MAIL] 12a NOOP|
|2024-08-21T12:11:14.606310249Z: DEBUG|▶ [MAIL] 12b 250 2.0.0 OK|
|2024-08-21T12:11:14.606363769Z: DEBUG|▶ [MAIL] 12c MAIL FROM:<mail@vikunja> BODY=8BITMIME|
|2024-08-21T12:11:14.607226961Z: DEBUG|▶ [MAIL] 12d 250 2.1.0 Sender OK|
|2024-08-21T12:11:14.607272073Z: DEBUG|▶ [MAIL] 12e RCPT TO:<thomas@domain.local>|
|2024-08-21T12:11:14.607993488Z: DEBUG|▶ [MAIL] 12f 250 2.1.5 Recipient OK|
|2024-08-21T12:11:14.60803436Z: DEBUG|▶ [MAIL] 130 DATA|
|2024-08-21T12:11:14.608614039Z: DEBUG|▶ [MAIL] 131 354 Start mail input; end with <CRLF>.<CRLF>|
|2024-08-21T12:11:14.715150965Z: DEBUG|▶ [MAIL] 132 NOOP|
|2024-08-21T12:11:14.71587348Z: DEBUG|▶ [MAIL] 133 250 2.0.0 OK|
|2024-08-21T12:11:14.715921769Z: DEBUG|▶ [MAIL] 134 RSET|
|2024-08-21T12:11:14.716585313Z: DEBUG|▶ [MAIL] 135 250 2.0.0 Resetting|
|2024-08-21T12:11:14.716626326Z: DEBUG|▶ [MAIL] 136 NOOP|
|2024-08-21T12:11:14.717168847Z: DEBUG|▶ [MAIL] 137 250 2.0.0 OK|
|2024-08-21T12:11:14.717250672Z: DEBUG|▶ [MAIL] 138 NOOP|
|2024-08-21T12:11:14.718114748Z: DEBUG|▶ [MAIL] 139 250 2.0.0 OK|
|2024-08-21T12:11:14.718170404Z: DEBUG|▶ [MAIL] 13a MAIL FROM:<mail@vikunja> BODY=8BITMIME|
|2024-08-21T12:11:14.719128308Z: DEBUG|▶ [MAIL] 13b 250 2.1.0 Sender OK|
|2024-08-21T12:11:14.719185525Z: DEBUG|▶ [MAIL] 13c RCPT TO:<thomas@domain.local>|
|2024-08-21T12:11:14.72008003Z: DEBUG|▶ [MAIL] 13d 250 2.1.5 Recipient OK|
|2024-08-21T12:11:14.720134123Z: DEBUG|▶ [MAIL] 13e DATA|
|2024-08-21T12:11:14.720841227Z: DEBUG|▶ [MAIL] 13f 354 Start mail input; end with <CRLF>.<CRLF>|
|2024-08-21T12:11:14.826050721Z: DEBUG|▶ [MAIL] 140 NOOP|
|2024-08-21T12:11:14.82676359Z: DEBUG|▶ [MAIL] 141 250 2.0.0 OK|
|2024-08-21T12:11:14.826810947Z: DEBUG|▶ [MAIL] 142 RSET|
|2024-08-21T12:11:14.82739771Z: DEBUG|▶ [MAIL] 143 250 2.0.0 Resetting|
|2024-08-21T12:11:14.827438089Z: DEBUG|▶ [MAIL] 144 NOOP|
|2024-08-21T12:11:14.828092016Z: DEBUG|▶ [MAIL] 145 250 2.0.0 OK|
```

Thank you

### Vikunja Version

Docker Version: v0.24.2

### Can you reproduce the bug on the Vikunja demo site?

No

**Comment by wusa88** [comment]
I think I have found the issue.

If i subscribe just to one task, the notification is shown once.
image
image
1603×643 67 KB

image
If i subscribe to the project, so every task is automatically subscribed, the notification is shown twice.
image
image
1750×621 75.2 KB

image
Maybe you could try this?

Whats best practice to get notifications from every task inside the project?
It’s just me and my teammate. We like to get every comments, that we stayed informed from each other.

**Comment by wusa88** [comment]
I think I have found the issue.

If i subscribe just to one task, the notification is shown once.
![image](https://github.com/user-attachments/assets/d35f9e8a-966f-48b2-9a58-7a35884d463e)
![image](https://github.com/user-attachments/assets/06a85c4f-1264-4644-b3a3-4a3b0aef8d70)

If i subscribe to the project, so every task is automatically subscribed, the notification is shown twice.
![image](https://github.com/user-attachments/assets/4b0af2a2-9f35-4498-838b-d1398c5ad200)
![image](https://github.com/user-attachments/assets/71d9cc7f-6d7f-47a6-9067-fc2d07e71ddb)

Maybe you could try this?

Whats best practice to get notifications from every task inside the project?
It’s just me and my teammate. We like to get every comments, that we stayed informed from each other.

**Comment by kolaente** [comment]
Fixed in https://github.com/go-vikunja/vikunja/commit/efde364224cf744c448a5b8e069776f18652d314, please check with the next unstable build (should be ready for deployment in ~45min, also on [try](https://try.vikunja.io)).
