### ISSUE TITLE
ServiceWorker script evaluation failed.

### ISSUE THREAD

**Issue by paulo-pertierra** [go-vikunja/vikunja#322]
### Description

On load, the service worker fails to register because "ServiceWorker script evaluation failed".

This was reproduced in my environment by creating a fresh install on Cloud Run, on docker.io/vikunja/vikunja:0.24.2 (currently the latest version). I'm not entirely sure why this is happening as I have no experience with service workers, but I believe this is the reason why caching doesn't work on my end.

I tried accessing the `/workbox-v7.0.0/workbox-sw.js` script and it doesn't return anything. But the service worker file `/sw.js` works.

![image](https://github.com/user-attachments/assets/f9f45695-d020-4baa-9d4d-7dd94109034d)
The Vikunja service worker can't be loaded on the demo site. 

![image](https://github.com/user-attachments/assets/a4c13efc-86d8-47ce-88be-0c9ca727c988)
A similar error happens on my own Docker deployment.

### Vikunja Version

0.24.2

### Browser and version

Google Chrome 128

### Can you reproduce the bug on the Vikunja demo site?

Yes

**Comment by paulo-pertierra** [comment]
I'd like to help if I can, I'll be doing some research and try if I can find a fix.

**Comment by kolaente** [comment]
Fixed in 165ee9e7f31893726f8a0f0bd22be0e035277e49, please check with the next unstable build (should be ready for deployment in ~45min, also on [try](https://try.vikunja.io)).
