### ISSUE TITLE
Cannot assign labels using while invoking PUT /tasks

### ISSUE THREAD

**Issue by cedroid09** [go-vikunja/vikunja#323]
### Description

I'm trying to assign a label a new tasks on creation:

Payload example:
`{'project_id': 14, 'title': 'New task', 'description': 'This is a new task', 'due_date': None, 'priority': 1, 'bucket_id': 0, 'labels': [{'id': 56, 'title': 'sync:todoist', 'description': 'Denotes all tasks in sync via Jaxto.', 'hex_color': '', 'created_by': {'id': 1, 'name': '', 'username': 'demo', 'created': '2021-05-30T10:45:25+02:00', 'updated': '2024-09-04T11:05:49+02:00'}, 'created': '2024-09-04T10:53:15+02:00', 'updated': '2024-09-04T10:53:15+02:00'}]}`

Response:
`
{'id': 242, 'title': 'New task', 'description': 'This is a new task', 'done': False, 'done_at': '0001-01-01T00:00:00Z', 'due_date': '0001-01-01T00:00:00Z', 'reminders': None, 'project_id': 14, 'repeat_after': 0, 'repeat_mode': 0, 'priority': 1, 'start_date': '0001-01-01T00:00:00Z', 'end_date': '0001-01-01T00:00:00Z', 'assignees': [], 'labels': [{'id': 56, 'title': 'sync:todoist', 'description': 'Denotes all tasks in sync via Jaxto.', 'hex_color': '', 'created_by': {'id': 1, 'name': '', 'username': 'demo', 'created': '2021-05-30T10:45:25+02:00', 'updated': '2024-09-04T10:50:31+02:00'}, 'created': '2024-09-04T10:53:15.104226106+02:00', 'updated': '2024-09-04T10:53:15.104228863+02:00'}], 'hex_color': '', 'percent_done': 0, 'identifier': '#39', 'index': 39, 'related_tasks': None, 'attachments': None, 'cover_image_attachment_id': 0, 'is_favorite': False, 'created': '2024-09-04T10:53:16.074875799+02:00', 'updated': '2024-09-04T10:53:16.074878244+02:00', 'bucket_id': 0, 'position': 2.384185791015625e-07, 'reactions': None, 'created_by': {'id': 1, 'name': '', 'username': 'demo', 'created': '2021-05-30T10:45:25+02:00', 'updated': '2024-09-04T10:50:31+02:00'}}
`

However, on the interface the tag is not assigned, nor can i see the assignment if do a get /tasks.

### Vikunja Version

v0.24.1-80-115d1c3618

### Can you reproduce the bug on the Vikunja demo site?

Yes

**Comment by kolaente** [comment]
That's not supported. It might be in the future, but currently there are no concrete plans to implement it.

PRs welcome!

**Comment by cedroid09** [comment]
Can you please mention that in the doc.
Would prevent someone from spending time debugging in the future ;)
