### ISSUE TITLE
"Invalid time value" error when trying to mark out realated tasks

### ISSUE THREAD

**Issue by majster95** [go-vikunja/vikunja#326]
### Description

Hi

When I try to mark out related task as done, then `Error Invalid time value` appears.
In task i set the correct due date so i think it should be fine.

I recorded a video to show exact bug.

### Vikunja Version

unstable

### Browser and version

Chrome 128.0.6613.138

### Can you reproduce the bug on the Vikunja demo site?

Yes

### Screenshots

https://github.com/user-attachments/assets/59c48a85-0ade-4129-ba30-c75671f92ae2

**Comment by kolaente** [comment]
Fixed in https://github.com/go-vikunja/vikunja/commit/ec902b051bcbb2c1382feb7c5ca0155d9d5fc4b7, please check with the next unstable build (should be ready for deployment in ~45min, also on [try](https://try.vikunja.io)).
