### ISSUE TITLE
Link share users cannot create tasks

### ISSUE THREAD

**Issue by kmbuthia** [go-vikunja/vikunja#331]
### Description

Users who can access a project on Vikunja via link share cannot create tasks even if their link is set to have an admin role.

### Vikunja Version

vikunja/vikunja:0.24.4

### Browser and version

Chrome browser

### Can you reproduce the bug on the Vikunja demo site?

No

### Screenshots

![screenshot](https://github.com/user-attachments/assets/37bc02b8-20db-41ac-8514-705701c640f6)

**Comment by kolaente** [comment]
Does this only happen in kanban?

**Comment by kmbuthia** [comment]
Thanks for getting back to me.
Yes it seems to work in list view. However only Kanban view throws the above error.

That said I tried testing the other views using the same link share with the link user set to admin and a different error is thrown on the Gantt view. Screenshot below.

<img width="1678" alt="Screenshot 2024-10-06 at 10 56 19" src="https://github.com/user-attachments/assets/fc47afa1-f41e-4f6b-989f-b28deb6b1f4c">

**Comment by kolaente** [comment]
I was unable to reproduce this. Can you reproduce it with the latest unstable build?

**Comment by kolaente** [comment]
Closing as inactive, please ping or open a new issue with relevant information if you still have this problem.
