### ISSUE TITLE
"Delete Project" button is shown even if no admin

### ISSUE THREAD

**Issue by MGChecker** [go-vikunja/vikunja#334]
### Description

If you are no admin for a project, but only have read/write permissions, you can still click the button, even though the final confirmation will end up raising a "403 Forbidden" error.

### Vikunja Version

0.24.4

### Browser and version

Firefox  130.0.1

### Can you reproduce the bug on the Vikunja demo site?

No

**Comment by kolaente** [comment]
Fixed in https://github.com/go-vikunja/vikunja/commit/92b90013abe06dfa98213a6b575a2fb63bc28908, please check with the next unstable build (should be ready for deployment in ~45min, also on [try](https://try.vikunja.io)).
