### ISSUE TITLE
CalDAV link not taking RP subpath into account

### ISSUE THREAD

**Issue by RayaneB75** [go-vikunja/vikunja#337]
### Description

If Vikunja is located under `http(s)://example.com/subpath` (following [Vikunja documentation](https://vikunja.io/docs/running-vikunja-in-a-subdirectory)), generated CalDAV link will always be  `http(s)://example.com/dav/...` instead of `http(s)://example.com/subpath/dav/...`

### Vikunja Version

v0.24.4

### Can you reproduce the bug on the Vikunja demo site?

No

### Screenshots

![Screenshot 2024-10-07 at 09 17 14](https://github.com/user-attachments/assets/b63a64ad-923d-41d6-bf18-fc07dc07a655)

**Comment by RayaneB75** [comment]
Yes I did.

**Comment by kolaente** [comment]
Fixed in https://github.com/go-vikunja/vikunja/commit/21af73ff931f68eeb1f81424b1ae79fdd4ed2921, please check with the next unstable build (should be ready for deployment in ~45min, also on [try](https://try.vikunja.io)).
