### ISSUE TITLE
'x' is null when clicking save button after creating task

### ISSUE THREAD

**Issue by m-GDEV** [go-vikunja/vikunja#338]
### Description

I am self hosting Vikunja. I was able to reproduce this on https://try.vikunja.io as well

To reproduce this error:
- Make new project (might not be necessary)
- Switch to kanban view
- Add new task
- Click on new task and press save button underneath the description section
- Error should pop up

### Vikunja Version

0.24.4

### Browser and version

Firefox 131.0 (64-bit) windows (I noticed Chrome shows more detailed errors)

### Can you reproduce the bug on the Vikunja demo site?

Yes

### Screenshots

https://github.com/user-attachments/assets/af9b0fd0-0ffd-451d-853d-000f67ea832c

**Comment by kolaente** [comment]
Fixed in https://github.com/go-vikunja/vikunja/commit/38964ace04a47e93ba30ad219560b9da32f38268, please check with the next unstable build (should be ready for deployment in ~45min, also on [try](https://try.vikunja.io)).
