### ISSUE TITLE
Gantt: This project view does not exist.

### ISSUE THREAD

**Issue by Sim0nW0lf** [go-vikunja/vikunja#340]
### Description

To reproduce this issue you need at least two projects. Now this issue occurs if you switch between projects and both have the Gantt view opened first.

I can reproduce this also in the demo when switching between the two projects and both are in Gantt view.

The issue is not only that the error pops up but the data also doesn't load.

Thanks for your awesome development 👍🏻

### Vikunja Version

v0.24.4

### Browser and version

Chrome

### Can you reproduce the bug on the Vikunja demo site?

Yes

### Screenshots

![image](https://github.com/user-attachments/assets/59930a53-52a0-4a00-96a0-f22c03e1a271)

**Comment by kolaente** [comment]
✨✨ Here's [an AI-assisted sketch of how you might approach this issue](https://copilot-workspace.githubnext.com/go-vikunja/vikunja/issues/340?shareId=87308814-1877-4dca-9262-d2cb6a5bf252) saved by @kolaente using Copilot Workspace v0.25

**Comment by kolaente** [comment]
Fixed in 5f5d93dfa026d9c6aac1cdc147874614e25867a0, please check with the next unstable build (should be ready for deployment in ~45min, also on [try](https://try.vikunja.io)).
