### ISSUE TITLE
Linked image missing of GitHub install badge

### ISSUE THREAD

**Issue by dpschen** [go-vikunja/vikunja#345]
See screenshot:

<img width="980" alt="Screenshot 2024-11-02 at 18 07 22" src="https://github.com/user-attachments/assets/5dd0653d-05ad-4da0-9601-0d4237e8299f">

**Comment by kolaente** [comment]
Fixed in https://github.com/go-vikunja/vikunja/commit/4238a5f6a3324ff26b86c893c09dcc38c7089c10
