### ISSUE TITLE
Tasks disappear from the kanban board in a saved filter when moving those to another project

### ISSUE THREAD

**Issue by Ma27** [go-vikunja/vikunja#348]
### Description

Can be reproduced like this:
* Create a label `foo`
* Create a project `foo`
* Create a project `bar`
* Create a task `task` in project `foo` with label `foo`
* Create a filter `filter` with filter expression `done = false && labels in foo`

As expected, the task `task` appears in the filter `filter` in the list view and the kanban view.

Now

* Move the task `task` to project `bar`

The task `task` is still visible in the list view of the `filter`, however it disappeared from the kanban view.

EDIT: it seems as if there's just a line missing in `task_buckets` for the task and the kanban view from the filter `filter`.

### Vikunja Version

0.24.4

### Can you reproduce the bug on the Vikunja demo site?

Yes

**Comment by Ma27** [comment]
Interestingly, when saving the filter after that, I see the task `task` I moved before twice in the kanban view. Once with its labels, once without.

**Comment by Ma27** [comment]
FYI I may have a working patch that. Will try to file a PR with it this weekend.

**Comment by Ma27** [comment]
OK I guess I need a confirmation in your gitea @kolaente

**Comment by kolaente** [comment]
Your account should be enabled now

**Comment by Ma27** [comment]
For anyone following here, there's a PR now on gitea: https://kolaente.dev/vikunja/vikunja/pulls/2840

**Comment by kolaente** [comment]
Resolved in https://kolaente.dev/vikunja/vikunja/pulls/2840
