### ISSUE TITLE
Internal server error when sorting by created in table view

### ISSUE THREAD

**Issue by kamalparyani** [go-vikunja/vikunja#350]
### Description

tested on try
Error is coming in projects and not in "saved filter"

### Vikunja Version

v0.24.1-408-3f62c013ba

### Browser and version

chrome 

### Can you reproduce the bug on the Vikunja demo site?

Yes

### Screenshots

![image](https://github.com/user-attachments/assets/be86e600-9e12-4e3e-a286-698272b56859)

**Comment by kamalparyani** [comment]
Error is coming in projects and not in "saved filter"

**Comment by guerman5** [comment]
Hi, good day for everyone
just want to double the report of this bug with a slight difference
Details:
All columns are sorting well, but when sorting the column 'Created' i get the Internal Server Error. Logs from docker show 

`2024-11-11T03:57:55Z: WEB 	▶ 192.168.16.225  GET 500 /api/v1/projects/2/views/21/tasks?sort_by[]=index&sort_by[]=created&order_by[]=desc&order_by[]=desc&filter=&filter_include_nulls=false&filter_timezone=Asia%2FTaipei&s=&expand=subtasks&page=1 2.142685ms - Mozilla/5.0 (X11; Linux x86_64; rv:131.0) Gecko/20100101 Firefox/131.0
2024-11-11T03:57:55Z: ERROR	▶ 1008 Error 1052 (23000): Column 'created' in order clause is ambiguous`

I'm aware that you need to reset the sorting of other columns to make single column sorting work as expected.

@kamalparyani 
in your screenshot i can see you have 2 sortings enabled, '#' and 'Created'.

**Comment by kolaente** [comment]
Fixed in feb6b708e367d1764cb2344af2563ad5481dba21, please check with the next unstable build (should be ready for deployment in ~45min, also on [try](https://try.vikunja.io)).
