### ISSUE TITLE
Import from v0.22.1 to v0.24.4 does not work

### ISSUE THREAD

**Issue by zero-thermo** [go-vikunja/vikunja#352]
### Description

Exporting from v0.22.1 and importing to v0.24.4 does not work.  

Steps to reproduce:
1. In v0.22.1, export to .zip via Settings >> Export
2. In v0.24.4, import from .zip via Settings >> Import

Expected behavior: all tasks, projects, and labels corrected imported

Observed behavior: Projects are not imported. Tasks are not imported (looks like only older completed tasks are added). Labels partially imported.

My v0.22.1 is setup via docker-compose using the separate vikunja/frontend and vikunja/api images with postgres:13. v0.24.4 uses a unified vikunja/vikunja image for both, and also updates to postgres:16. I'm not sure how to correctly update, so would like to export to the latest Vikunja version

### Vikunja Version

v0.22.1 and v0.24.4

### Can you reproduce the bug on the Vikunja demo site?

No

**Comment by kolaente** [comment]
Importing from older versions is not supported. You must be on the same version as the one you exported from.

Upgrade instructions to the unified container are here: https://vikunja.io/changelog/whats-new-in-vikunja-0.23.0#how-to-upgrade
