### ISSUE TITLE
Reminders default to 1st January 1970

### ISSUE THREAD

**Issue by AlexChesters** [go-vikunja/vikunja#359]
### Description

Reminders seem to default to 1st January 1970, this is a bit unintuitive given it's 50 years in the past 😄 

### Vikunja Version

v0.24.4 (via docker)

### Can you reproduce the bug on the Vikunja demo site?

Yes

### Screenshots

<img width="1609" alt="Screenshot 2024-11-19 at 10 02 38" src="https://github.com/user-attachments/assets/d285e5c3-d028-4f39-8280-3f3eb2305c96">

**Comment by kolaente** [comment]
Fixed in e02ebbcba1a9af9ead65c0597e94a15f965c9498, please check with the next unstable build (should be ready for deployment in ~45min, also on [try](https://try.vikunja.io)).
