### ISSUE TITLE
Clicking On a Related Task opens a massive window with no close button.

### ISSUE THREAD

**Issue by Escapekent** [go-vikunja/vikunja#360]
### Description

When clicking on a related task from a task it opens the related task full window size and has no close button. The only way to close it is to click on a project instead. 
Preferably it would have a back button but even just having it open the standard size with a close option would be fine.

On the demo site its slightly different where the window it opens is even bigger.

### Vikunja Version

Version: v0.24.4

### Browser and version

Edge and chrome

### Can you reproduce the bug on the Vikunja demo site?

Yes

### Screenshots

![Screenshot 2024-11-21 101131](https://github.com/user-attachments/assets/7682086e-e281-4fcb-a157-55eb38f64b0f)
![Screenshot 2024-11-21 101147](https://github.com/user-attachments/assets/1a811c23-6a0e-4826-885e-fce12a2c1c1c)

**Comment by kolaente** [comment]
Fixed in 80f8570e2212f16586c67db8fa015468f3b6f683, please check with the next unstable build (should be ready for deployment in ~45min, also on [try](https://try.vikunja.io)).
