### ISSUE TITLE
Marking a task done through the api removes the cover image

### ISSUE THREAD

**Issue by bthornton191** [go-vikunja/vikunja#361]
### Vikunja Version

v0.24.4

### Can you reproduce the bug on the Vikunja demo site?

Yes

### Screenshots

# Initial
![image](https://github.com/user-attachments/assets/11d1fee7-a42a-4390-b8c7-0cd504ca4104)

# Api Call
![image](https://github.com/user-attachments/assets/9e641672-156b-4dcf-a03b-7825241f074f)

# After api call
![image](https://github.com/user-attachments/assets/049c6f1d-7095-46b0-8a9d-ac0c805034e2)

**Comment by kolaente** [comment]
Seems like you didn't pass the cover image in your update request. That's interpreted as "remove the cover image" - and other properties, like the description.

Due to limitations in Go, we don't have a way to reliably check if you didn't pass the value or reset it.
