### ISSUE TITLE
Health check not available

### ISSUE THREAD

**Issue by holtgrewe** [go-vikunja/vikunja#363]
### Description

First of all: thanks for providing this super useful web app. Also, even more thanks for naming it after a camelid species which is awesome!

The `Dockerfile` specifies a `HEALTHCHECK`

https://github.com/go-vikunja/vikunja/blob/89f3caaa525013f071a005460811d6cb66efb04b/Dockerfile#L56-L57

However, the CLI apparently does not have this available

```
$ docker exec -it vikunja-docker-compose-vikunja-1 /app/vikunja/vikunja version
Vikunja api version v0.24.5
Built with go1.23.3
$ docker exec -it vikunja-docker-compose-vikunja-1 /app/vikunja/vikunja healthcheck
Error: unknown command "healthcheck" for "vikunja"
Run 'vikunja --help' for usage.
unknown command "healthcheck" for "vikunja"
```

Of course, there is `http://localhost:3456/heatlh` ... **but** because there is no `curl` or even `bash` ([see this nice trick for HTTP requests without curl-less bash](https://medium.com/bash-tips-and-tricks/part01-tcp-udp-request-with-a-native-bash-feature-and-without-curl-wget-9dcef59c30aa), I don't see how to properly implement a `HEALTHCHECK` in my docker compose.

So it appears that:

- `vikunja healthcheck` CLI command is missing
- OR the Dockerfile is wrong or does something I don't understand

Possible resolutions as far as I can see:

- add `vikunja healthcheck`
- OR remove the lines from the dockerfile
    - in this case, please either give the user a `bash`, `grep`, and potentially a `curl` so they can implement `HEALTHCHECK`

### Vikunja Version

0.24.5

### Can you reproduce the bug on the Vikunja demo site?

No

**Comment by kolaente** [comment]
The command has been implemented recently (see [this pr](https://kolaente.dev/vikunja/vikunja/pulls/2856)) but it hasn't been released yet to a stable release.
