### ISSUE TITLE
Add note to documentation incorrect about case of filter fields in api

### ISSUE THREAD

**Issue by bthornton191** [go-vikunja/vikunja#365]
### Description

The documentation at https://vikunja.io/docs/filters has everything in camel case. But the api returns everything in snake. Maybe I should have known, but a note in the docs would have saved me some time time and headache. 🙏

That section of the docs is correct for the front end, but the api ref links to it. The api ref might be the a good place to note the discrepancy.

```python
>>> url = 'https://***************/api/v1/projects/2/tasks'
>>> response = requests.get(url, headers=headers)
>>> for k in response.json()[0]:
>>>    print(k) 
id
title
description
done
done_at
due_date
reminders
project_id
repeat_after
repeat_mode
priority
start_date
end_date
assignees
labels
hex_color
percent_done
identifier
index
related_tasks
attachments
cover_image_attachment_id
is_favorite
created
updated
bucket_id
position
reactions
created_by
```

### Vikunja Version

0.24.4

### Can you reproduce the bug on the Vikunja demo site?

Please select

### Screenshots

![image](https://github.com/user-attachments/assets/86192833-818d-40cb-8c52-bdb76b2af1ca)

**Comment by kolaente** [comment]
Thanks for the report! This is now fixed (might take a while until visible on the website).
