### ISSUE TITLE
Line break (\n) support when using API

### ISSUE THREAD

**Issue by chark1es** [go-vikunja/vikunja#369]
### Description

When using the API to create a task, specifically for the "description" field, there is no way to make a line break with \n. When trying to include \n in the description field, it gets parsed out from the html.

### Vikunja Version

v0.24.5

### Can you reproduce the bug on the Vikunja demo site?

No

**Comment by kolaente** [comment]
What exactly is the expected behaviour here? Since the frontend renders the description as html, it will not count `\n` as a line break. If you want the frontend to show a line break, you need to set a `<br/>` via the api.

**Comment by chark1es** [comment]
Oh I see. I didnt know that I would be able to do that with html.
