### ISSUE TITLE
"Import your projects" welcome message persists after import.

### ISSUE THREAD

**Issue by Coyote21** [go-vikunja/vikunja#372]
### Description

I've already imported my data from Todoist, I've configured most of Vikunja to my liking, but I still have the "Import your projects and tasks" section, taking up lots of real-estate, especially when using PWA on a mobile, at the top of my Overview.

### Vikunja Version

v0.24.5

### Browser and version

Primary Browser is Brave on Arch Linux, But have tested with other chrome and Firefox based browsers

### Can you reproduce the bug on the Vikunja demo site?

No

### Screenshots

![vikunja_ss](https://github.com/user-attachments/assets/24325856-ddf3-4cd6-a5e4-9ab22b8137f1)

**Comment by kolaente** [comment]
Does this depend on the device? Or are you seeing this across all devices?

**Comment by kolaente** [comment]
After checking how this will be shown, do you have a saved filter set for the tasks on the overview page?

**Comment by Coyote21** [comment]
I've tried using Firefox on my desktop, no change, the import section is still present. I've still have not got around to trying FF on my phone but I'm not expecting any changes.

Yes!, I am using a saved filter for my Overview page and when I don't, the import section is NOT displayed.  So it is definitely the saved filter as Overview that causes the issue.

**Comment by kolaente** [comment]
I was able to reproduce this with a filter set to home, fixed in 6f9b0ddfe7aa8a77b7d758742a41bb512a2f2797. Please check with the next unstable build (should be ready for deployment in ~45min, also on [try](https://try.vikunja.io)).
