### ISSUE TITLE
Cannot install vikunja without systemd

### ISSUE THREAD

**Issue by mjk-gh** [go-vikunja/vikunja#382]
### Description

I downloaded the [Debian](https://dl.vikunja.io/vikunja/0.24.6/vikunja-0.24.6-amd64.deb) package for Vikunja and tried to install it, but it would not install, because systemd is missing (and cannot be installed on my system, which uses SysV-init):

```
# dpkg -i vikunja-0.24.6-amd64.deb
Selecting previously unselected package vikunja.
(Reading database ... 672346 files and directories currently installed.)
Preparing to unpack vikunja-0.24.6-amd64.deb ...
Unpacking vikunja (0.24.6) ...
dpkg: dependency problems prevent configuration of vikunja:
 vikunja depends on systemd; however:
  Package systemd is not installed.

dpkg: error processing package vikunja (--install):
 dependency problems - leaving unconfigured
Errors were encountered while processing:
 vikunja
#
```

Vikunja _does_ get installed and seems to work just fine, it is just that a SysV init script is missing.

I converted the installed Vikunja systemd service file using [systemd-to-sysvinit-converter](https://github.com/akhilvij/systemd-to-sysvinit-converter) like so:

```
python converter.py vikunja.service > /etc/init.d/vikunja
```

... hacked it a little to make vikunja start in the background (I have next to no knowledge about either init system, SysV or Systemd), and finally, created the start and stop links to the SysV init script:

```
update-rc.d vikunja defaults
```

Vikunja can be started and stopped using this SysV script (but not be monitored with it, that would need some more tweaking), see [attached file](https://github.com/user-attachments/files/18246785/vikunja.txt) (remove .txt extension, github seems to need a file extension for uploaded files).

I cannot get the accompanying Vikunja desktop package to run, though ("Error: Cannot find module 'body-parser'"), and "npm install body-parser" fails with
```
# npm install body-parser
npm ERR! code UNABLE_TO_GET_ISSUER_CERT_LOCALLY
npm ERR! errno UNABLE_TO_GET_ISSUER_CERT_LOCALLY
npm ERR! request to https://registry.npmjs.org/body-parser failed, reason: unable to get local issuer certificate

npm ERR! A complete log of this run can be found in:
npm ERR!     /root/.npm/_logs/2024-12-24T21_08_15_818Z-debug-0.log
```
and I am not sure if I am willing to use something like
```
npm config set strict-ssl false
```

But maybe this bug report helps other people with SysV-init based Linux installation.

### Vikunja Version

0.24.6

### Can you reproduce the bug on the Vikunja demo site?

Please select

**Comment by kolaente** [comment]
It's unlikely that we'll officially support other init systems than systemd on debian, simply because it is the standard and supporting multiple different ones in one package isn't exactly easy. You can always install Vikunja manually if that standard doesn't fit your use-case.

> I cannot get the accompanying Vikunja desktop package to run, though ("Error: Cannot find module 'body-parser'"), and "npm install body-parser" fails with

This sounds like your certificate store is broken. Does it work with a [release desktop package](https://dl.vikunja.io/desktop)?

**Comment by kevlar700** [comment]
Same issue for Devuan for obvious reasons. For anyone else coming across this I think the manual install method is the "Install from binary" section at https://vikunja.io/docs/installing/

Tip: You can use doas or sudo to securely run vikunja as a vikunja or custom user even with a nologin shell.
