### ISSUE TITLE
Unable to list newly created users - Fresh Docker install

### ISSUE THREAD

**Issue by Gamechiefx** [go-vikunja/vikunja#92]
### Description

I am having an issue with this as well:

Install Type: Docker

Version: Latest

Created Users via API, Registration, CLI

Problem: Unable to see created user to assign task or projects. I am able to login as the created users utilizing the above methods.

Please assist.

### Vikunja Frontend Version

Latest

### Vikunja API Version

Latest

### Browser and version

Latest Chrome

### Can you reproduce the bug on the Vikunja demo site?

Yes

**Comment by kolaente** [comment]
Please provide clear steps to reproduce.
