### ISSUE TITLE
Feature Request: Home Assistant To-do List Integration

### ISSUE THREAD

**Issue by bepstein111** [go-vikunja/vikunja#94]
Home Assistant just released a new update which included the addition of to-do lists into Home Assistant. The only way Vikunja could make my life more convenient is by having an integration for Home Assistant so I can display my Vikunja tasks with the rest of my home dashboard. Thanks for all you do!

**Comment by kolaente** [comment]
I've moved it now to the api, probably fits better here but unsure still. I'd say it's definitely not app-related though.

---

Do you have any information on how To-Do lists work in Home Assistant? Should this be a sync-feature from Home Assistant's to-do list to Vikunja, or should it be more like a widget with an embed of Vikunja?

**Comment by gravelfreeman** [comment]
Personally once I have time I'll check out to-do lists in HA and it might be exactly what I need  for smaller recurrent tasks. Then would use Vikunja for big projects.

**Comment by pinpox** [comment]
Isn't this something to be implemented on HA's side? Home-assistant has integrations for about everything upon earth, I guess there could be a vikunja integration doing what you want?

**Comment by gravelfreeman** [comment]
Like you said, they've got so many things already integrated. Anything you're asking on their forums or Github gets buried down quickly. I feel like the best place to speak about this is here.

**Comment by Craftoncu** [comment]
+1, but its not an Feature Request for this project. It should be done as @pinpox said already. It has to be an integration. 

If someone wants collab. I would sacrifice myself to create one.
Not a big deal, a bit hass framework, css and some rest calls.
But I'm a noob in css.

**Comment by Craftoncu** [comment]
Nevermind, I'll start right now.

**Comment by pinpox** [comment]
> Nevermind, I'll start right now.

Not sure how much time I'll find right now to help develop, but let me know if I can help with testing

**Comment by Craftoncu** [comment]
So, quick status. I managed to access vikunja through an hass adapter. I already get projects and their tasks. But I found out, that Python is completely different than Java or GoLang

**Comment by Craftoncu** [comment]
Update again. The Integration seems working. I will do a few tests then I will release it below:

https://github.com/craftoncu/hacs-vikunja-integration

![image](https://github.com/go-vikunja/api/assets/55136417/e2c6ee19-7fff-4ed2-82c1-77f1ad566073)

**Comment by gravelfreeman** [comment]
That's some great news, thank you so much for taking the time in developing this extension. I'll try it and report back to you once it's on your Github.

**Comment by Craftoncu** [comment]
No worries! 
I uploaded the code into GitHub. 

https://github.com/Craftoncu/hacs-vikunja-integration

But there is still one issue, you're currently not able to mark a task as done. There is some home -assistant logic which I don't understand right now. And I literally never worked that much with python. 

Maybe one of you finds this issue.  I will fix the lint errors and push the changes in a few minutes.

**Comment by kolaente** [comment]
Closing this since we now have the extension from @Craftoncu - Thanks!

**Comment by pinpox** [comment]
> But there is still one issue, you're currently not able to mark a task as done. 

@Craftoncu was this issue ever fixed or is it still open? If so It might be worth creating an issue for it.
